using KeyNekretnine.Domain.PhoneNumbers;

namespace KeyNekretnine.Infrastructure.Configuration.SeedData;
public class PhoneData
{
    public static List<PhoneNumber> GetPhoneNumbers()
    {
        var phoneNumbers = new List<PhoneNumber>()
        {

            new PhoneNumber{ Id = 1, Code = "AD", Label = "Andorra", Phone = "376" },
            new PhoneNumber{ Id = 2, Code = "AE", Label = "United Arab Emirates", Phone = "971" },
            new PhoneNumber{ Id = 3, Code = "AF", Label = "Afghanistan", Phone = "93" },
            new PhoneNumber{ Id = 4, Code = "AG", Label = "Antigua and Barbuda", Phone = "1-268" },
            new PhoneNumber{ Id = 5, Code = "AI", Label = "Anguilla", Phone = "1-264" },
            new PhoneNumber{ Id = 6, Code = "AL", Label = "Albania", Phone = "355" },
            new PhoneNumber{ Id = 7, Code = "AM", Label = "Armenia", Phone = "374" },
            new PhoneNumber{ Id = 8, Code = "AO", Label = "Angola", Phone = "244" },
            new PhoneNumber{ Id = 9, Code = "AQ", Label = "Antarctica", Phone = "672" },
            new PhoneNumber{ Id = 10, Code = "AR", Label = "Argentina", Phone = "54" },
            new PhoneNumber{ Id = 11, Code = "AS", Label = "American Samoa", Phone = "1-684" },
            new PhoneNumber{ Id = 12, Code = "AT", Label = "Austria", Phone = "43" },
            new PhoneNumber{ Id = 13, Code = "AU", Label = "Australia", Phone = "61" },
            new PhoneNumber{ Id = 14, Code = "AW", Label = "Aruba", Phone = "297" },
            new PhoneNumber{ Id = 15, Code = "AX", Label = "Alland Islands", Phone = "358" },
            new PhoneNumber{ Id = 16, Code = "AZ", Label = "Azerbaijan", Phone = "994" },
            new PhoneNumber{ Id = 17, Code = "BA", Label = "Bosnia and Herzegovina", Phone = "387" },
            new PhoneNumber{ Id = 18, Code = "BB", Label = "Barbados", Phone = "1-246" },
            new PhoneNumber{ Id = 19, Code = "BD", Label = "Bangladesh", Phone = "880" },
            new PhoneNumber{ Id = 20, Code = "BE", Label = "Belgium", Phone = "32" },
            new PhoneNumber{ Id = 21, Code = "BF", Label = "Burkina Faso", Phone = "226" },
            new PhoneNumber{ Id = 22, Code = "BG", Label = "Bulgaria", Phone = "359" },
            new PhoneNumber{ Id = 23, Code = "BH", Label = "Bahrain", Phone = "973" },
            new PhoneNumber{ Id = 24, Code = "BI", Label = "Burundi", Phone = "257" },
            new PhoneNumber{ Id = 25, Code = "BJ", Label = "Benin", Phone = "229" },
            new PhoneNumber{ Id = 26, Code = "BL", Label = "Saint Barthelemy", Phone = "590" },
            new PhoneNumber{ Id = 27, Code = "BM", Label = "Bermuda", Phone = "1-441" },
            new PhoneNumber{ Id = 28, Code = "BN", Label = "Brunei Darussalam", Phone = "673" },
            new PhoneNumber{ Id = 29, Code = "BO", Label = "Bolivia", Phone = "591" },
            new PhoneNumber{ Id = 30, Code = "BR", Label = "Brazil", Phone = "55" },
            new PhoneNumber{ Id = 31, Code = "BS", Label = "Bahamas", Phone = "1-242" },
            new PhoneNumber{ Id = 32, Code = "BT", Label = "Bhutan", Phone = "975" },
            new PhoneNumber{ Id = 33, Code = "BV", Label = "Bouvet Island", Phone = "47" },
            new PhoneNumber{ Id = 34, Code = "BW", Label = "Botswana", Phone = "267" },
            new PhoneNumber{ Id = 35, Code = "BY", Label = "Belarus", Phone = "375" },
            new PhoneNumber{ Id = 36, Code = "BZ", Label = "Belize", Phone = "501" },
            new PhoneNumber{ Id = 37, Code = "CA", Label = "Canada", Phone = "1" },
            new PhoneNumber{ Id = 38, Code = "CC", Label = "Cocos (Keeling) Islands", Phone = "61" },
            new PhoneNumber{ Id = 39, Code = "CD", Label = "Congo, Democratic Republic of the", Phone = "243" },
            new PhoneNumber{ Id = 40, Code = "CF", Label = "Central African Republic", Phone = "236" },
            new PhoneNumber{ Id = 41, Code = "CG", Label = "Congo, Republic of the", Phone = "242" },
            new PhoneNumber{ Id = 42, Code = "CH", Label = "Switzerland", Phone = "41" },
            new PhoneNumber{ Id = 43, Code = "CI", Label = "Cote d'Ivoire", Phone = "225" },
            new PhoneNumber{ Id = 44, Code = "CK", Label = "Cook Islands", Phone = "682" },
            new PhoneNumber{ Id = 45, Code = "CL", Label = "Chile", Phone = "56" },
            new PhoneNumber{ Id = 46, Code = "CM", Label = "Cameroon", Phone = "237" },
            new PhoneNumber{ Id = 47, Code = "CN", Label = "China", Phone = "86" },
            new PhoneNumber{ Id = 48, Code = "CO", Label = "Colombia", Phone = "57" },
            new PhoneNumber{ Id = 49, Code = "CR", Label = "Costa Rica", Phone = "506" },
            new PhoneNumber{ Id = 50, Code = "CU", Label = "Cuba", Phone = "53" },
            new PhoneNumber{ Id = 51, Code = "CV", Label = "Cape Verde", Phone = "238" },
            new PhoneNumber{ Id = 52, Code = "CW", Label = "Curacao", Phone = "599" },
            new PhoneNumber{ Id = 53, Code = "CX", Label = "Christmas Island", Phone = "61" },
            new PhoneNumber{ Id = 54, Code = "CY", Label = "Cyprus", Phone = "357" },
            new PhoneNumber{ Id = 55, Code = "CZ", Label = "Czech Republic", Phone = "420" },
            new PhoneNumber{ Id = 56, Code = "DE", Label = "Germany", Phone = "49" },
            new PhoneNumber{ Id = 57, Code = "DJ", Label = "Djibouti", Phone = "253" },
            new PhoneNumber{ Id = 58, Code = "DK", Label = "Denmark", Phone = "45" },
            new PhoneNumber{ Id = 59, Code = "DM", Label = "Dominica", Phone = "1-767" },
            new PhoneNumber{ Id = 60, Code = "DO", Label = "Dominican Republic", Phone = "1-809" },
            new PhoneNumber{ Id = 61, Code = "DZ", Label = "Algeria", Phone = "213" },
            new PhoneNumber{ Id = 62, Code = "EC", Label = "Ecuador", Phone = "593" },
            new PhoneNumber{ Id = 63, Code = "EE", Label = "Estonia", Phone = "372" },
            new PhoneNumber{ Id = 64, Code = "EG", Label = "Egypt", Phone = "20" },
            new PhoneNumber{ Id = 65, Code = "EH", Label = "Western Sahara", Phone = "212" },
            new PhoneNumber{ Id = 66, Code = "ER", Label = "Eritrea", Phone = "291" },
            new PhoneNumber{ Id = 67, Code = "ES", Label = "Spain", Phone = "34" },
            new PhoneNumber{ Id = 68, Code = "ET", Label = "Ethiopia", Phone = "251" },
            new PhoneNumber{ Id = 69, Code = "FI", Label = "Finland", Phone = "358" },
            new PhoneNumber{ Id = 70, Code = "FJ", Label = "Fiji", Phone = "679" },
            new PhoneNumber{ Id = 71, Code = "FK", Label = "Falkland Islands (Malvinas)", Phone = "500" },
            new PhoneNumber{ Id = 72, Code = "FM", Label = "Micronesia, Federated States of", Phone = "691" },
            new PhoneNumber{ Id = 73, Code = "FO", Label = "Faroe Islands", Phone = "298" },
            new PhoneNumber{ Id = 74, Code = "FR", Label = "France", Phone = "33" },
            new PhoneNumber{ Id = 75, Code = "GA", Label = "Gabon", Phone = "241" },
            new PhoneNumber{ Id = 76, Code = "GB", Label = "United Kingdom", Phone = "44" },
            new PhoneNumber{ Id = 77, Code = "GD", Label = "Grenada", Phone = "1-473" },
            new PhoneNumber{ Id = 78, Code = "GE", Label = "Georgia", Phone = "995" },
            new PhoneNumber{ Id = 79, Code = "GF", Label = "French Guiana", Phone = "594" },
            new PhoneNumber{ Id = 80, Code = "GG", Label = "Guernsey", Phone = "44" },
            new PhoneNumber{ Id = 81, Code = "GH", Label = "Ghana", Phone = "233" },
            new PhoneNumber{ Id = 82, Code = "GI", Label = "Gibraltar", Phone = "350" },
            new PhoneNumber{ Id = 83, Code = "GL", Label = "Greenland", Phone = "299" },
            new PhoneNumber{ Id = 84, Code = "GM", Label = "Gambia", Phone = "220" },
            new PhoneNumber{ Id = 85, Code = "GN", Label = "Guinea", Phone = "224" },
            new PhoneNumber{ Id = 86, Code = "GP", Label = "Guadeloupe", Phone = "590" },
            new PhoneNumber{ Id = 87, Code = "GQ", Label = "Equatorial Guinea", Phone = "240" },
            new PhoneNumber{ Id = 88, Code = "GR", Label = "Greece", Phone = "30" },
            new PhoneNumber{ Id = 89, Code = "GS", Label = "South Georgia and the South Sandwich Islands", Phone = "500" },
            new PhoneNumber{ Id = 90, Code = "GT", Label = "Guatemala", Phone = "502" },
            new PhoneNumber{ Id = 91, Code = "GU", Label = "Guam", Phone = "1-671" },
            new PhoneNumber{ Id = 92, Code = "GW", Label = "Guinea-Bissau", Phone = "245" },
            new PhoneNumber{ Id = 93, Code = "GY", Label = "Guyana", Phone = "592" },
            new PhoneNumber{ Id = 94, Code = "HK", Label = "Hong Kong", Phone = "852" },
            new PhoneNumber{ Id = 95, Code = "HM", Label = "Heard Island and McDonald Islands", Phone = "672" },
            new PhoneNumber{ Id = 96, Code = "HN", Label = "Honduras", Phone = "504" },
            new PhoneNumber{ Id = 97, Code = "HR", Label = "Croatia", Phone = "385" },
            new PhoneNumber{ Id = 98, Code = "HT", Label = "Haiti", Phone = "509" },
            new PhoneNumber{ Id = 99, Code = "HU", Label = "Hungary", Phone = "36" },
            new PhoneNumber{ Id = 100, Code = "ID", Label = "Indonesia", Phone = "62" },
            new PhoneNumber{ Id = 101, Code = "IE", Label = "Ireland", Phone = "353" },
            new PhoneNumber{ Id = 102, Code = "IL", Label = "Israel", Phone = "972" },
            new PhoneNumber{ Id = 103, Code = "IM", Label = "Isle of Man", Phone = "44" },
            new PhoneNumber{ Id = 104, Code = "IN", Label = "India", Phone = "91" },
            new PhoneNumber{ Id = 105, Code = "IO", Label = "British Indian Ocean Territory", Phone = "246" },
            new PhoneNumber{ Id = 106, Code = "IQ", Label = "Iraq", Phone = "964" },
            new PhoneNumber{ Id = 107, Code = "IR", Label = "Iran, Islamic Republic of", Phone = "98" },
            new PhoneNumber{ Id = 108, Code = "IS", Label = "Iceland", Phone = "354" },
            new PhoneNumber{ Id = 109, Code = "IT", Label = "Italy", Phone = "39" },
            new PhoneNumber{ Id = 110, Code = "JE", Label = "Jersey", Phone = "44" },
            new PhoneNumber{ Id = 111, Code = "JM", Label = "Jamaica", Phone = "1-876" },
            new PhoneNumber{ Id = 112, Code = "JO", Label = "Jordan", Phone = "962" },
            new PhoneNumber{ Id = 113, Code = "JP", Label = "Japan", Phone = "81" },
            new PhoneNumber{ Id = 114, Code = "KE", Label = "Kenya", Phone = "254" },
            new PhoneNumber{ Id = 115, Code = "KG", Label = "Kyrgyzstan", Phone = "996" },
            new PhoneNumber{ Id = 116, Code = "KH", Label = "Cambodia", Phone = "855" },
            new PhoneNumber{ Id = 117, Code = "KI", Label = "Kiribati", Phone = "686" },
            new PhoneNumber{ Id = 118, Code = "KM", Label = "Comoros", Phone = "269" },
            new PhoneNumber{ Id = 119, Code = "KN", Label = "Saint Kitts and Nevis", Phone = "1-869" },
            new PhoneNumber{ Id = 120, Code = "KP", Label = "Korea, Democratic People's Republic of", Phone = "850" },
            new PhoneNumber{ Id = 121, Code = "KR", Label = "Korea, Republic of", Phone = "82" },
            new PhoneNumber{ Id = 122, Code = "KW", Label = "Kuwait", Phone = "965" },
            new PhoneNumber{ Id = 123, Code = "KY", Label = "Cayman Islands", Phone = "1-345" },
            new PhoneNumber{ Id = 124, Code = "KZ", Label = "Kazakhstan", Phone = "7" },
            new PhoneNumber{ Id = 125, Code = "LA", Label = "Lao People's Democratic Republic", Phone = "856" },
            new PhoneNumber{ Id = 126, Code = "LB", Label = "Lebanon", Phone = "961" },
            new PhoneNumber{ Id = 127, Code = "LC", Label = "Saint Lucia", Phone = "1-758" },
            new PhoneNumber{ Id = 128, Code = "LI", Label = "Liechtenstein", Phone = "423" },
            new PhoneNumber{ Id = 129, Code = "LK", Label = "Sri Lanka", Phone = "94" },
            new PhoneNumber{ Id = 130, Code = "LR", Label = "Liberia", Phone = "231" },
            new PhoneNumber{ Id = 131, Code = "LS", Label = "Lesotho", Phone = "266" },
            new PhoneNumber{ Id = 132, Code = "LT", Label = "Lithuania", Phone = "370" },
            new PhoneNumber{ Id = 133, Code = "LU", Label = "Luxembourg", Phone = "352" },
            new PhoneNumber{ Id = 134, Code = "LV", Label = "Latvia", Phone = "371" },
            new PhoneNumber{ Id = 135, Code = "LY", Label = "Libya", Phone = "218" },
            new PhoneNumber{ Id = 136, Code = "MA", Label = "Morocco", Phone = "212" },
            new PhoneNumber{ Id = 137, Code = "MC", Label = "Monaco", Phone = "377" },
            new PhoneNumber{ Id = 138, Code = "MD", Label = "Moldova, Republic of", Phone = "373" },
            new PhoneNumber{ Id = 139, Code = "ME", Label = "Montenegro", Phone = "382" },
            new PhoneNumber{ Id = 140, Code = "MF", Label = "Saint Martin (French part)", Phone = "590" },
            new PhoneNumber{ Id = 141, Code = "MG", Label = "Madagascar", Phone = "261" },
            new PhoneNumber{ Id = 142, Code = "MH", Label = "Marshall Islands", Phone = "692" },
            new PhoneNumber{ Id = 143, Code = "MK", Label = "Macedonia, the Former Yugoslav Republic of", Phone = "389" },
            new PhoneNumber{ Id = 144, Code = "ML", Label = "Mali", Phone = "223" },
            new PhoneNumber{ Id = 145, Code = "MM", Label = "Myanmar", Phone = "95" },
            new PhoneNumber{ Id = 146, Code = "MN", Label = "Mongolia", Phone = "976" },
            new PhoneNumber{ Id = 147, Code = "MO", Label = "Macao", Phone = "853" },
            new PhoneNumber{ Id = 148, Code = "MP", Label = "Northern Mariana Islands", Phone = "1-670" },
            new PhoneNumber{ Id = 149, Code = "MQ", Label = "Martinique", Phone = "596" },
            new PhoneNumber{ Id = 150, Code = "MR", Label = "Mauritania", Phone = "222" },
            new PhoneNumber{ Id = 151, Code = "MS", Label = "Montserrat", Phone = "1-664" },
            new PhoneNumber{ Id = 152, Code = "MT", Label = "Malta", Phone = "356" },
            new PhoneNumber{ Id = 153, Code = "MU", Label = "Mauritius", Phone = "230" },
            new PhoneNumber{ Id = 154, Code = "MV", Label = "Maldives", Phone = "960" },
            new PhoneNumber{ Id = 155, Code = "MW", Label = "Malawi", Phone = "265" },
            new PhoneNumber{ Id = 156, Code = "MX", Label = "Mexico", Phone = "52" },
            new PhoneNumber{ Id = 157, Code = "MY", Label = "Malaysia", Phone = "60" },
            new PhoneNumber{ Id = 158, Code = "MZ", Label = "Mozambique", Phone = "258" },
            new PhoneNumber{ Id = 159, Code = "NA", Label = "Namibia", Phone = "264" },
            new PhoneNumber{ Id = 160, Code = "NC", Label = "New Caledonia", Phone = "687" },
            new PhoneNumber{ Id = 161, Code = "NE", Label = "Niger", Phone = "227" },
            new PhoneNumber{ Id = 162, Code = "NF", Label = "Norfolk Island", Phone = "672" },
            new PhoneNumber{ Id = 163, Code = "NG", Label = "Nigeria", Phone = "234" },
            new PhoneNumber{ Id = 164, Code = "NI", Label = "Nicaragua", Phone = "505" },
            new PhoneNumber{ Id = 165, Code = "NL", Label = "Netherlands", Phone = "31" },
            new PhoneNumber{ Id = 166, Code = "NO", Label = "Norway", Phone = "47" },
            new PhoneNumber{ Id = 167, Code = "NP", Label = "Nepal", Phone = "977" },
            new PhoneNumber{ Id = 168, Code = "NR", Label = "Nauru", Phone = "674" },
            new PhoneNumber{ Id = 169, Code = "NU", Label = "Niue", Phone = "683" },
            new PhoneNumber{ Id = 170, Code = "NZ", Label = "New Zealand", Phone = "64" },
            new PhoneNumber{ Id = 171, Code = "OM", Label = "Oman", Phone = "968" },
            new PhoneNumber{ Id = 172, Code = "PA", Label = "Panama", Phone = "507" },
            new PhoneNumber{ Id = 173, Code = "PE", Label = "Peru", Phone = "51" },
            new PhoneNumber{ Id = 174, Code = "PF", Label = "French Polynesia", Phone = "689" },
            new PhoneNumber{ Id = 175, Code = "PG", Label = "Papua New Guinea", Phone = "675" },
            new PhoneNumber{ Id = 176, Code = "PH", Label = "Philippines", Phone = "63" },
            new PhoneNumber{ Id = 177, Code = "PK", Label = "Pakistan", Phone = "92" },
            new PhoneNumber{ Id = 178, Code = "PL", Label = "Poland", Phone = "48" },
            new PhoneNumber{ Id = 179, Code = "PM", Label = "Saint Pierre and Miquelon", Phone = "508" },
            new PhoneNumber{ Id = 180, Code = "PN", Label = "Pitcairn", Phone = "870" },
            new PhoneNumber{ Id = 181, Code = "PR", Label = "Puerto Rico", Phone = "1" },
            new PhoneNumber{ Id = 182, Code = "PS", Label = "Palestine, State of", Phone = "970" },
            new PhoneNumber{ Id = 183, Code = "PT", Label = "Portugal", Phone = "351" },
            new PhoneNumber{ Id = 184, Code = "PW", Label = "Palau", Phone = "680" },
            new PhoneNumber{ Id = 185, Code = "PY", Label = "Paraguay", Phone = "595" },
            new PhoneNumber{ Id = 186, Code = "QA", Label = "Qatar", Phone = "974" },
            new PhoneNumber{ Id = 187, Code = "RE", Label = "Reunion", Phone = "262" },
            new PhoneNumber{ Id = 188, Code = "RO", Label = "Romania", Phone = "40" },
            new PhoneNumber{ Id = 189, Code = "RS", Label = "Serbia", Phone = "381" },
            new PhoneNumber{ Id = 190, Code = "RU", Label = "Russian Federation", Phone = "7" },
            new PhoneNumber{ Id = 191, Code = "RW", Label = "Rwanda", Phone = "250" },
            new PhoneNumber{ Id = 192, Code = "SA", Label = "Saudi Arabia", Phone = "966" },
            new PhoneNumber{ Id = 193, Code = "SB", Label = "Solomon Islands", Phone = "677" },
            new PhoneNumber{ Id = 194, Code = "SC", Label = "Seychelles", Phone = "248" },
            new PhoneNumber{ Id = 195, Code = "SD", Label = "Sudan", Phone = "249" },
            new PhoneNumber{ Id = 196, Code = "SE", Label = "Sweden", Phone = "46" },
            new PhoneNumber{ Id = 197, Code = "SG", Label = "Singapore", Phone = "65" },
            new PhoneNumber{ Id = 198, Code = "SH", Label = "Saint Helena", Phone = "290" },
            new PhoneNumber{ Id = 199, Code = "SI", Label = "Slovenia", Phone = "386" },
            new PhoneNumber{ Id = 200, Code = "SJ", Label = "Svalbard and Jan Mayen", Phone = "47" },
            new PhoneNumber{ Id = 201, Code = "SK", Label = "Slovakia", Phone = "421" },
            new PhoneNumber{ Id = 202, Code = "SL", Label = "Sierra Leone", Phone = "232" },
            new PhoneNumber{ Id = 203, Code = "SM", Label = "San Marino", Phone = "378" },
            new PhoneNumber{ Id = 204, Code = "SN", Label = "Senegal", Phone = "221" },
            new PhoneNumber{ Id = 205, Code = "SO", Label = "Somalia", Phone = "252" },
            new PhoneNumber{ Id = 206, Code = "SR", Label = "Suriname", Phone = "597" },
            new PhoneNumber{ Id = 207, Code = "SS", Label = "South Sudan", Phone = "211" },
            new PhoneNumber{ Id = 208, Code = "ST", Label = "Sao Tome and Principe", Phone = "239" },
            new PhoneNumber{ Id = 209, Code = "SV", Label = "El Salvador", Phone = "503" },
            new PhoneNumber{ Id = 210, Code = "SX", Label = "Sint Maarten (Dutch part)", Phone = "1-721" },
            new PhoneNumber{ Id = 211, Code = "SY", Label = "Syrian Arab Republic", Phone = "963" },
            new PhoneNumber{ Id = 212, Code = "SZ", Label = "Swaziland", Phone = "268" },
            new PhoneNumber{ Id = 213, Code = "TC", Label = "Turks and Caicos Islands", Phone = "1-649" },
            new PhoneNumber{ Id = 214, Code = "TD", Label = "Chad", Phone = "235" },
            new PhoneNumber{ Id = 215, Code = "TF", Label = "French Southern Territories", Phone = "262" },
            new PhoneNumber{ Id = 216, Code = "TG", Label = "Togo", Phone = "228" },
            new PhoneNumber{ Id = 217, Code = "TH", Label = "Thailand", Phone = "66" },
            new PhoneNumber{ Id = 218, Code = "TJ", Label = "Tajikistan", Phone = "992" },
            new PhoneNumber{ Id = 219, Code = "TK", Label = "Tokelau", Phone = "690" },
            new PhoneNumber{ Id = 220, Code = "TL", Label = "Timor-Leste", Phone = "670" },
            new PhoneNumber{ Id = 221, Code = "TM", Label = "Turkmenistan", Phone = "993" },
            new PhoneNumber{ Id = 222, Code = "TN", Label = "Tunisia", Phone = "216" },
            new PhoneNumber{ Id = 223, Code = "TO", Label = "Tonga", Phone = "676" },
            new PhoneNumber{ Id = 224, Code = "TR", Label = "Turkey", Phone = "90" },
            new PhoneNumber{ Id = 225, Code = "TT", Label = "Trinidad and Tobago", Phone = "1-868" },
            new PhoneNumber{ Id = 226, Code = "TV", Label = "Tuvalu", Phone = "688" },
            new PhoneNumber{ Id = 227, Code = "TW", Label = "Taiwan, Republic of China", Phone = "886" },
            new PhoneNumber{ Id = 228, Code = "TZ", Label = "United Republic of Tanzania", Phone = "255" },
            new PhoneNumber{ Id = 229, Code = "UA", Label = "Ukraine", Phone = "380" },
            new PhoneNumber{ Id = 230, Code = "UG", Label = "Uganda", Phone = "256" },
            new PhoneNumber{ Id = 231, Code = "US", Label = "United States", Phone = "1" },
            new PhoneNumber{ Id = 232, Code = "UY", Label = "Uruguay", Phone = "598" },
            new PhoneNumber{ Id = 233, Code = "UZ", Label = "Uzbekistan", Phone = "998" },
            new PhoneNumber{ Id = 234, Code = "VA", Label = "Holy See (Vatican City State)", Phone = "379" },
            new PhoneNumber{ Id = 235, Code = "VC", Label = "Saint Vincent and the Grenadines", Phone = "1-784" },
            new PhoneNumber{ Id = 236, Code = "VE", Label = "Venezuela", Phone = "58" },
            new PhoneNumber{ Id = 237, Code = "VG", Label = "British Virgin Islands", Phone = "1-284" },
            new PhoneNumber{ Id = 238, Code = "VI", Label = "US Virgin Islands", Phone = "1-340" },
            new PhoneNumber{ Id = 239, Code = "VN", Label = "Vietnam", Phone = "84" },
            new PhoneNumber{ Id = 240, Code = "VU", Label = "Vanuatu", Phone = "678" },
            new PhoneNumber{ Id = 241, Code = "WF", Label = "Wallis and Futuna", Phone = "681" },
            new PhoneNumber{ Id = 242, Code = "WS", Label = "Samoa", Phone = "685" },
            new PhoneNumber{ Id = 243, Code = "XK", Label = "Kosovo", Phone = "383" },
            new PhoneNumber{ Id = 244, Code = "YE", Label = "Yemen", Phone = "967" },
            new PhoneNumber{ Id = 245, Code = "YT", Label = "Mayotte", Phone = "262" },
            new PhoneNumber{ Id = 246, Code = "ZA", Label = "South Africa", Phone = "27" },
            new PhoneNumber{ Id = 247, Code = "ZM", Label = "Zambia", Phone = "260" },
            new PhoneNumber{ Id = 248, Code = "ZW", Label = "Zimbabwe", Phone = "263" }
        };

        return phoneNumbers;
    }
}
