using KeyNekretnine.Domain.Neighborhoods;

namespace KeyNekretnine.Infrastructure.Configuration.SeedData;
public class NeighborhoodData
{
    public static List<Neighborhood> GetNeighborhoods()
    {
        var neighborhoods = new List<Neighborhood>()
            {
                new Neighborhood{Id = 1, Name = "Andželati", CityId = 1},
                new Neighborhood{Id = 2, Name = "Božići", CityId = 1},
                new Neighborhood{Id = 3, Name = "Bojovići", CityId = 1},
                new Neighborhood{Id = 4, Name = "Gnjili Potok", CityId = 1},
                new Neighborhood{Id = 5, Name = "Gračanica", CityId = 1},
                new Neighborhood{Id = 6, Name = "Dulipolje", CityId = 1},
                new Neighborhood{Id = 7, Name = "Đulići", CityId = 1},
                new Neighborhood{Id = 8, Name = "Zabrđe", CityId = 1},
                new Neighborhood{Id = 9, Name = "Jošanica", CityId = 1},
                new Neighborhood{Id = 10, Name = "Košutići", CityId = 1},
                new Neighborhood{Id = 11, Name = "Kralje", CityId = 1},
                new Neighborhood{Id = 12, Name = "Kuti", CityId = 1},
                new Neighborhood{Id = 13, Name = "Gornje Luge", CityId = 1},
                new Neighborhood{Id = 14, Name = "Rijeka Marsenića", CityId = 1},
                new Neighborhood{Id = 15, Name = "Prisoja", CityId = 1},
                new Neighborhood{Id = 16, Name = "Seoca", CityId = 1},
                new Neighborhood{Id = 17, Name = "Sjenožeta", CityId = 1},
                new Neighborhood{Id = 18, Name = "Slatina", CityId = 1},
                new Neighborhood{Id = 19, Name = "Trepča", CityId = 1},
                new Neighborhood{Id = 20, Name = "Trešnjevo", CityId = 1},
                new Neighborhood{Id = 21, Name = "Ulotina", CityId = 1},
                new Neighborhood{Id = 22, Name = "Cecuni", CityId = 1},
                new Neighborhood{Id = 23, Name = "Arbnež", CityId = 2},
                new Neighborhood{Id = 24, Name = "Bar", CityId = 2},
                new Neighborhood{Id = 25, Name = "Bartula", CityId = 2},
                new Neighborhood{Id = 26, Name = "Besa", CityId = 2},
                new Neighborhood{Id = 27, Name = "Bjeliši", CityId = 2},
                new Neighborhood{Id = 28, Name = "Bobovište", CityId = 2},
                new Neighborhood{Id = 29, Name = "Boljevići", CityId = 2},
                new Neighborhood{Id = 30, Name = "Braćeni", CityId = 2},
                new Neighborhood{Id = 31, Name = "Brijege", CityId = 2},
                new Neighborhood{Id = 32, Name = "Brca", CityId = 2},
                new Neighborhood{Id = 33, Name = "Bukovik", CityId = 2},
                new Neighborhood{Id = 34, Name = "Burtaiši", CityId = 2},
                new Neighborhood{Id = 35, Name = "Velembusi", CityId = 2},
                new Neighborhood{Id = 36, Name = "Veliki Mikulići", CityId = 2},
                new Neighborhood{Id = 37, Name = "Veliki Ostros", CityId = 2},
                new Neighborhood{Id = 38, Name = "Velja Gorana", CityId = 2},
                new Neighborhood{Id = 39, Name = "Velje Selo", CityId = 2},
                new Neighborhood{Id = 40, Name = "Virpazar", CityId = 2},
                new Neighborhood{Id = 41, Name = "Gluhi Do", CityId = 2},
                new Neighborhood{Id = 42, Name = "Godinje", CityId = 2},
                new Neighborhood{Id = 43, Name = "Gornja Briska", CityId = 2},
                new Neighborhood{Id = 44, Name = "Gornji Brčeli", CityId = 2},
                new Neighborhood{Id = 45, Name = "Gornji Murići", CityId = 2},
                new Neighborhood{Id = 46, Name = "Grdovići", CityId = 2},
                new Neighborhood{Id = 47, Name = "Gurza", CityId = 2},
                new Neighborhood{Id = 48, Name = "Dabezići", CityId = 2},
                new Neighborhood{Id = 49, Name = "Dedići", CityId = 2},
                new Neighborhood{Id = 50, Name = "Dobra Voda", CityId = 2},
                new Neighborhood{Id = 51, Name = "Donja Briska", CityId = 2},
                new Neighborhood{Id = 52, Name = "Donji Brčeli", CityId = 2},
                new Neighborhood{Id = 53, Name = "Donji Murići", CityId = 2},
                new Neighborhood{Id = 54, Name = "Dračevica", CityId = 2},
                new Neighborhood{Id = 55, Name = "Dupilo", CityId = 2},
                new Neighborhood{Id = 56, Name = "Đenđinovići", CityId = 2},
                new Neighborhood{Id = 57, Name = "Đuravci", CityId = 2},
                new Neighborhood{Id = 58, Name = "Đurmani", CityId = 2},
                new Neighborhood{Id = 59, Name = "Zagrađe", CityId = 2},
                new Neighborhood{Id = 60, Name = "Zaljevo", CityId = 2},
                new Neighborhood{Id = 61, Name = "Zankovići", CityId = 2},
                new Neighborhood{Id = 62, Name = "Zgrade", CityId = 2},
                new Neighborhood{Id = 63, Name = "Zupci", CityId = 2},
                new Neighborhood{Id = 64, Name = "Karanikići", CityId = 2},
                new Neighborhood{Id = 65, Name = "Komarno", CityId = 2},
                new Neighborhood{Id = 66, Name = "Koštanjica", CityId = 2},
                new Neighborhood{Id = 67, Name = "Krnjice", CityId = 2},
                new Neighborhood{Id = 68, Name = "Kruševica", CityId = 2},
                new Neighborhood{Id = 69, Name = "Kunje", CityId = 2},
                new Neighborhood{Id = 70, Name = "Livari", CityId = 2},
                new Neighborhood{Id = 71, Name = "Limljani", CityId = 2},
                new Neighborhood{Id = 72, Name = "Lukići", CityId = 2},
                new Neighborhood{Id = 73, Name = "Mala Gorana", CityId = 2},
                new Neighborhood{Id = 74, Name = "Mali Mikulići", CityId = 2},
                new Neighborhood{Id = 75, Name = "Mali Ostros", CityId = 2},
                new Neighborhood{Id = 76, Name = "Marstijepovići", CityId = 2},
                new Neighborhood{Id = 77, Name = "Martići", CityId = 2},
                new Neighborhood{Id = 78, Name = "Mačuge", CityId = 2},
                new Neighborhood{Id = 79, Name = "Miljevci", CityId = 2},
                new Neighborhood{Id = 80, Name = "Mišići", CityId = 2},
                new Neighborhood{Id = 81, Name = "Ovtočići", CityId = 2},
                new Neighborhood{Id = 82, Name = "Orahovo", CityId = 2},
                new Neighborhood{Id = 83, Name = "Papani", CityId = 2},
                new Neighborhood{Id = 84, Name = "Pelinkovići", CityId = 2},
                new Neighborhood{Id = 85, Name = "Pečurice", CityId = 2},
                new Neighborhood{Id = 86, Name = "Pinčići", CityId = 2},
                new Neighborhood{Id = 87, Name = "Podi", CityId = 2},
                new Neighborhood{Id = 88, Name = "Polje", CityId = 2},
                new Neighborhood{Id = 89, Name = "Popratnica", CityId = 2},
                new Neighborhood{Id = 90, Name = "Seoca", CityId = 2},
                new Neighborhood{Id = 91, Name = "Sozina", CityId = 2},
                new Neighborhood{Id = 92, Name = "Sotonići", CityId = 2},
                new Neighborhood{Id = 93, Name = "Stari Bar", CityId = 2},
                new Neighborhood{Id = 94, Name = "Sustaš", CityId = 2},
                new Neighborhood{Id = 95, Name = "Sutomore", CityId = 2},
                new Neighborhood{Id = 96, Name = "Tejani", CityId = 2},
                new Neighborhood{Id = 97, Name = "Tomba", CityId = 2},
                new Neighborhood{Id = 98, Name = "Tomići", CityId = 2},
                new Neighborhood{Id = 99, Name = "Trnovo", CityId = 2},
                new Neighborhood{Id = 100, Name = "Tuđemili", CityId = 2},
                new Neighborhood{Id = 101, Name = "Turčini", CityId = 2},
                new Neighborhood{Id = 102, Name = "Utrg", CityId = 2},
                new Neighborhood{Id = 103, Name = "Ckla", CityId = 2},
                new Neighborhood{Id = 104, Name = "Čeluga", CityId = 2},
                new Neighborhood{Id = 105, Name = "Šušanj", CityId = 2},
                new Neighborhood{Id = 106, Name = "Brajkovača", CityId = 3},
                new Neighborhood{Id = 107, Name = "Virak", CityId = 3},
                new Neighborhood{Id = 108, Name = "Vrela", CityId = 3},
                new Neighborhood{Id = 109, Name = "Gomile", CityId = 3},
                new Neighborhood{Id = 110, Name = "Gradina", CityId = 3},
                new Neighborhood{Id = 111, Name = "Dobri Nugo", CityId = 3},
                new Neighborhood{Id = 112, Name = "Zminica", CityId = 3},
                new Neighborhood{Id = 113, Name = "Krš", CityId = 3},
                new Neighborhood{Id = 114, Name = "Motički Gaj", CityId = 3},
                new Neighborhood{Id = 115, Name = "Ninkovići", CityId = 3},
                new Neighborhood{Id = 116, Name = "Novakovići", CityId = 3},
                new Neighborhood{Id = 117, Name = "Njegovuđa", CityId = 3},
                new Neighborhood{Id = 118, Name = "Palež", CityId = 3},
                new Neighborhood{Id = 119, Name = "Pašina Voda", CityId = 3},
                new Neighborhood{Id = 120, Name = "Pašino Polje", CityId = 3},
                new Neighborhood{Id = 121, Name = "Pitomine", CityId = 3},
                new Neighborhood{Id = 122, Name = "Podgora", CityId = 3},
                new Neighborhood{Id = 123, Name = "Pošćenski Kraj", CityId = 3},
                new Neighborhood{Id = 124, Name = "Rasova", CityId = 3},
                new Neighborhood{Id = 125, Name = "Rudanci", CityId = 3},
                new Neighborhood{Id = 126, Name = "Suvodo", CityId = 3},
                new Neighborhood{Id = 127, Name = "Tepačko Polje", CityId = 3},
                new Neighborhood{Id = 128, Name = "Tepca", CityId = 3},
                new Neighborhood{Id = 129, Name = "Mala Crna Gora", CityId = 3},
                new Neighborhood{Id = 130, Name = "Šljivansko", CityId = 3},
                new Neighborhood{Id = 131, Name = "Šumanovac", CityId = 3},
                new Neighborhood{Id = 132, Name = "Borje", CityId = 3},
                new Neighborhood{Id = 133, Name = "Bare", CityId = 4},
                new Neighborhood{Id = 134, Name = "Boan", CityId = 4},
                new Neighborhood{Id = 135, Name = "Godijelji", CityId = 4},
                new Neighborhood{Id = 136, Name = "Gornja Bijela", CityId = 4},
                new Neighborhood{Id = 137, Name = "Gornja Bukovica", CityId = 4},
                new Neighborhood{Id = 138, Name = "Grabovica", CityId = 4},
                new Neighborhood{Id = 139, Name = "Dobra Sela", CityId = 4},
                new Neighborhood{Id = 140, Name = "Donja Bijela", CityId = 4},
                new Neighborhood{Id = 141, Name = "Donja Bukovica", CityId = 4},
                new Neighborhood{Id = 142, Name = "Dubrovsko", CityId = 4},
                new Neighborhood{Id = 143, Name = "Duži", CityId = 4},
                new Neighborhood{Id = 144, Name = "Komarnica", CityId = 4},
                new Neighborhood{Id = 145, Name = "Krnja Jela", CityId = 4},
                new Neighborhood{Id = 146, Name = "Malinsko", CityId = 4},
                new Neighborhood{Id = 147, Name = "Miloševići", CityId = 4},
                new Neighborhood{Id = 148, Name = "Mljetičak", CityId = 4},
                new Neighborhood{Id = 149, Name = "Mokro", CityId = 4},
                new Neighborhood{Id = 150, Name = "Petnjica", CityId = 4},
                new Neighborhood{Id = 151, Name = "Pošćenje", CityId = 4},
                new Neighborhood{Id = 152, Name = "Previš", CityId = 4},
                new Neighborhood{Id = 153, Name = "Pridvorica", CityId = 4},
                new Neighborhood{Id = 154, Name = "Provalija", CityId = 4},
                new Neighborhood{Id = 155, Name = "Slatina", CityId = 4},
                new Neighborhood{Id = 156, Name = "Strug", CityId = 4},
                new Neighborhood{Id = 157, Name = "Timar", CityId = 4},
                new Neighborhood{Id = 158, Name = "Tušina", CityId = 4},
                new Neighborhood{Id = 159, Name = "Azane", CityId = 5},
                new Neighborhood{Id = 160, Name = "Babino", CityId = 5},
                new Neighborhood{Id = 161, Name = "Bastahe", CityId = 5},
                new Neighborhood{Id = 162, Name = "Beran Selo", CityId = 5},
                new Neighborhood{Id = 163, Name = "Bor", CityId = 5},
                new Neighborhood{Id = 164, Name = "Bubanje", CityId = 5},
                new Neighborhood{Id = 165, Name = "Budimlja", CityId = 5},
                new Neighborhood{Id = 166, Name = "Buče", CityId = 5},
                new Neighborhood{Id = 167, Name = "Veliđe", CityId = 5},
                new Neighborhood{Id = 168, Name = "Vinicka", CityId = 5},
                new Neighborhood{Id = 169, Name = "Vrševo", CityId = 5},
                new Neighborhood{Id = 170, Name = "Vuča", CityId = 5},
                new Neighborhood{Id = 171, Name = "Glavaca", CityId = 5},
                new Neighborhood{Id = 172, Name = "Godočelje", CityId = 5},
                new Neighborhood{Id = 173, Name = "Goražde", CityId = 5},
                new Neighborhood{Id = 174, Name = "Gornja Vrbica", CityId = 5},
                new Neighborhood{Id = 175, Name = "Gornje Zaostro", CityId = 5},
                new Neighborhood{Id = 176, Name = "Dapsići", CityId = 5},
                new Neighborhood{Id = 177, Name = "Dašča Rijeka", CityId = 5},
                new Neighborhood{Id = 178, Name = "Dobrodole", CityId = 5},
                new Neighborhood{Id = 179, Name = "Dolac", CityId = 5},
                new Neighborhood{Id = 180, Name = "Donja Vrbica", CityId = 5},
                new Neighborhood{Id = 181, Name = "Donja Ržanica", CityId = 5},
                new Neighborhood{Id = 182, Name = "Donje Zaostro", CityId = 5},
                new Neighborhood{Id = 183, Name = "Dragosava", CityId = 5},
                new Neighborhood{Id = 184, Name = "Zagorje", CityId = 5},
                new Neighborhood{Id = 185, Name = "Zagrad", CityId = 5},
                new Neighborhood{Id = 186, Name = "Zagrađe", CityId = 5},
                new Neighborhood{Id = 187, Name = "Javorova", CityId = 5},
                new Neighborhood{Id = 188, Name = "Johovica", CityId = 5},
                new Neighborhood{Id = 189, Name = "Jašovići", CityId = 5},
                new Neighborhood{Id = 190, Name = "Kalica", CityId = 5},
                new Neighborhood{Id = 191, Name = "Kaludra", CityId = 5},
                new Neighborhood{Id = 192, Name = "Krušča", CityId = 5},
                new Neighborhood{Id = 193, Name = "Kurikuće", CityId = 5},
                new Neighborhood{Id = 194, Name = "Lagatori", CityId = 5},
                new Neighborhood{Id = 195, Name = "Lazi", CityId = 5},
                new Neighborhood{Id = 196, Name = "Lubnice", CityId = 5},
                new Neighborhood{Id = 197, Name = "Donje Luge", CityId = 5},
                new Neighborhood{Id = 198, Name = "Lužac", CityId = 5},
                new Neighborhood{Id = 199, Name = "Lješnica", CityId = 5},
                new Neighborhood{Id = 200, Name = "Mašte", CityId = 5},
                new Neighborhood{Id = 201, Name = "Mezgalji", CityId = 5},
                new Neighborhood{Id = 202, Name = "Murovac", CityId = 5},
                new Neighborhood{Id = 203, Name = "Orah", CityId = 5},
                new Neighborhood{Id = 204, Name = "Orahovo", CityId = 5},
                new Neighborhood{Id = 205, Name = "Pahulj", CityId = 5},
                new Neighborhood{Id = 206, Name = "Petnjik", CityId = 5},
                new Neighborhood{Id = 207, Name = "Petnjica", CityId = 5},
                new Neighborhood{Id = 208, Name = "Pešca", CityId = 5},
                new Neighborhood{Id = 209, Name = "Ponor", CityId = 5},
                new Neighborhood{Id = 210, Name = "Poroče", CityId = 5},
                new Neighborhood{Id = 211, Name = "Praćevac", CityId = 5},
                new Neighborhood{Id = 212, Name = "Radmanci", CityId = 5},
                new Neighborhood{Id = 213, Name = "Radmuževići", CityId = 5},
                new Neighborhood{Id = 214, Name = "Rovca", CityId = 5},
                new Neighborhood{Id = 215, Name = "Rujišta", CityId = 5},
                new Neighborhood{Id = 216, Name = "Savin Bor", CityId = 5},
                new Neighborhood{Id = 217, Name = "Skakavac", CityId = 5},
                new Neighborhood{Id = 218, Name = "Tmušići", CityId = 5},
                new Neighborhood{Id = 219, Name = "Trpezi", CityId = 5},
                new Neighborhood{Id = 220, Name = "Tucanje", CityId = 5},
                new Neighborhood{Id = 221, Name = "Crvljevine", CityId = 5},
                new Neighborhood{Id = 222, Name = "Crni Vrh", CityId = 5},
                new Neighborhood{Id = 223, Name = "Štitari", CityId = 5},
                new Neighborhood{Id = 224, Name = "Bajice", CityId = 6},
                new Neighborhood{Id = 225, Name = "Barjamovica", CityId = 6},
                new Neighborhood{Id = 226, Name = "Bijele Poljane", CityId = 6},
                new Neighborhood{Id = 227, Name = "Bjeloši", CityId = 6},
                new Neighborhood{Id = 228, Name = "Bobija", CityId = 6},
                new Neighborhood{Id = 229, Name = "Boguti", CityId = 6},
                new Neighborhood{Id = 230, Name = "Bokovo", CityId = 6},
                new Neighborhood{Id = 231, Name = "Velestovo", CityId = 6},
                new Neighborhood{Id = 232, Name = "Vignjevići", CityId = 6},
                new Neighborhood{Id = 233, Name = "Vojkovići", CityId = 6},
                new Neighborhood{Id = 234, Name = "Vrba", CityId = 6},
                new Neighborhood{Id = 235, Name = "Vrela", CityId = 6},
                new Neighborhood{Id = 236, Name = "Vuči Do", CityId = 6},
                new Neighborhood{Id = 237, Name = "Gadji", CityId = 6},
                new Neighborhood{Id = 238, Name = "Gornja Zaljut", CityId = 6},
                new Neighborhood{Id = 239, Name = "Gornji Ceklin", CityId = 6},
                new Neighborhood{Id = 240, Name = "Grab", CityId = 6},
                new Neighborhood{Id = 241, Name = "Gradina", CityId = 6},
                new Neighborhood{Id = 242, Name = "Gradjani", CityId = 6},
                new Neighborhood{Id = 243, Name = "Dide", CityId = 6},
                new Neighborhood{Id = 244, Name = "Dobrska Župa", CityId = 6},
                new Neighborhood{Id = 245, Name = "Dobrsko Selo", CityId = 6},
                new Neighborhood{Id = 246, Name = "Dodoši", CityId = 6},
                new Neighborhood{Id = 247, Name = "Donja Zaljut", CityId = 6},
                new Neighborhood{Id = 248, Name = "Donje Selo", CityId = 6},
                new Neighborhood{Id = 249, Name = "Dragomi Do", CityId = 6},
                new Neighborhood{Id = 250, Name = "Drušići", CityId = 6},
                new Neighborhood{Id = 251, Name = "Dubovik", CityId = 6},
                new Neighborhood{Id = 252, Name = "Dubovo", CityId = 6},
                new Neighborhood{Id = 253, Name = "Dugi Do", CityId = 6},
                new Neighborhood{Id = 254, Name = "Dujeva", CityId = 6},
                new Neighborhood{Id = 255, Name = "Djalci", CityId = 6},
                new Neighborhood{Id = 256, Name = "Djinovići", CityId = 6},
                new Neighborhood{Id = 257, Name = "Erakovići", CityId = 6},
                new Neighborhood{Id = 258, Name = "Žanjev Do", CityId = 6},
                new Neighborhood{Id = 259, Name = "Zabrdje", CityId = 6},
                new Neighborhood{Id = 260, Name = "Zagora", CityId = 6},
                new Neighborhood{Id = 261, Name = "Začir", CityId = 6},
                new Neighborhood{Id = 262, Name = "Izvori", CityId = 6},
                new Neighborhood{Id = 263, Name = "Jankovići", CityId = 6},
                new Neighborhood{Id = 264, Name = "Jezer", CityId = 6},
                new Neighborhood{Id = 265, Name = "Kobilji Do", CityId = 6},
                new Neighborhood{Id = 266, Name = "Kopito", CityId = 6},
                new Neighborhood{Id = 267, Name = "Kosijeri", CityId = 6},
                new Neighborhood{Id = 268, Name = "Kranji Do", CityId = 6},
                new Neighborhood{Id = 269, Name = "Kućišta", CityId = 6},
                new Neighborhood{Id = 270, Name = "Lastva", CityId = 6},
                new Neighborhood{Id = 271, Name = "Lipa", CityId = 6},
                new Neighborhood{Id = 272, Name = "Lješev Stub", CityId = 6},
                new Neighborhood{Id = 273, Name = "Majstori", CityId = 6},
                new Neighborhood{Id = 274, Name = "Malošin Do", CityId = 6},
                new Neighborhood{Id = 275, Name = "Markovina", CityId = 6},
                new Neighborhood{Id = 276, Name = "Meterizi", CityId = 6},
                new Neighborhood{Id = 277, Name = "Mikulići", CityId = 6},
                new Neighborhood{Id = 278, Name = "Milijevići", CityId = 6},
                new Neighborhood{Id = 279, Name = "Mužovići", CityId = 6},
                new Neighborhood{Id = 280, Name = "Njeguši", CityId = 6},
                new Neighborhood{Id = 281, Name = "Obzovica", CityId = 6},
                new Neighborhood{Id = 282, Name = "Ožegovice", CityId = 6},
                new Neighborhood{Id = 283, Name = "Oćevići", CityId = 6},
                new Neighborhood{Id = 284, Name = "Očinići", CityId = 6},
                new Neighborhood{Id = 285, Name = "Pačaradje", CityId = 6},
                new Neighborhood{Id = 286, Name = "Pejovići", CityId = 6},
                new Neighborhood{Id = 287, Name = "Petrov Do", CityId = 6},
                new Neighborhood{Id = 288, Name = "Poda", CityId = 6},
                new Neighborhood{Id = 289, Name = "Podbukovica", CityId = 6},
                new Neighborhood{Id = 290, Name = "Prevlaka", CityId = 6},
                new Neighborhood{Id = 291, Name = "Prediš", CityId = 6},
                new Neighborhood{Id = 292, Name = "Prekornica", CityId = 6},
                new Neighborhood{Id = 293, Name = "Prentin Do", CityId = 6},
                new Neighborhood{Id = 294, Name = "Proseni Do", CityId = 6},
                new Neighborhood{Id = 295, Name = "Radomir", CityId = 6},
                new Neighborhood{Id = 296, Name = "Raičevići", CityId = 6},
                new Neighborhood{Id = 297, Name = "Rvaši", CityId = 6},
                new Neighborhood{Id = 298, Name = "Resna", CityId = 6},
                new Neighborhood{Id = 299, Name = "Ržani Do", CityId = 6},
                new Neighborhood{Id = 300, Name = "Rijeka Crnojevića", CityId = 6},
                new Neighborhood{Id = 301, Name = "Riječani", CityId = 6},
                new Neighborhood{Id = 302, Name = "Rokoči", CityId = 6},
                new Neighborhood{Id = 303, Name = "Smokovci", CityId = 6},
                new Neighborhood{Id = 304, Name = "Tomići", CityId = 6},
                new Neighborhood{Id = 305, Name = "Trešnjevo", CityId = 6},
                new Neighborhood{Id = 306, Name = "Trnjine", CityId = 6},
                new Neighborhood{Id = 307, Name = "Uba", CityId = 6},
                new Neighborhood{Id = 308, Name = "Ubli", CityId = 6},
                new Neighborhood{Id = 309, Name = "Ublice", CityId = 6},
                new Neighborhood{Id = 310, Name = "Ugnji", CityId = 6},
                new Neighborhood{Id = 311, Name = "Ulići", CityId = 6},
                new Neighborhood{Id = 312, Name = "Čevo", CityId = 6},
                new Neighborhood{Id = 313, Name = "Češljari", CityId = 6},
                new Neighborhood{Id = 314, Name = "Šinđon", CityId = 6},
                new Neighborhood{Id = 315, Name = "Štitari", CityId = 6},
                new Neighborhood{Id = 316, Name = "Bare Šumanovića", CityId = 7},
                new Neighborhood{Id = 317, Name = "Begovina", CityId = 7},
                new Neighborhood{Id = 318, Name = "Bileća", CityId = 7},
                new Neighborhood{Id = 319, Name = "Bobulja", CityId = 7},
                new Neighborhood{Id = 320, Name = "Bogićevići", CityId = 7},
                new Neighborhood{Id = 321, Name = "Boronjina", CityId = 7},
                new Neighborhood{Id = 322, Name = "Brajovići", CityId = 7},
                new Neighborhood{Id = 323, Name = "Braćani", CityId = 7},
                new Neighborhood{Id = 324, Name = "Brijestovo", CityId = 7},
                new Neighborhood{Id = 325, Name = "Veleta", CityId = 7},
                new Neighborhood{Id = 326, Name = "Vinići", CityId = 7},
                new Neighborhood{Id = 327, Name = "Viš", CityId = 7},
                new Neighborhood{Id = 328, Name = "Vučica", CityId = 7},
                new Neighborhood{Id = 329, Name = "Gorica", CityId = 7},
                new Neighborhood{Id = 330, Name = "Gornji Martinići", CityId = 7},
                new Neighborhood{Id = 331, Name = "Gornji Rsojevići", CityId = 7},
                new Neighborhood{Id = 332, Name = "Gostilje Brajovićko", CityId = 7},
                new Neighborhood{Id = 333, Name = "Gostilje Martinićko", CityId = 7},
                new Neighborhood{Id = 334, Name = "Gradina", CityId = 7},
                new Neighborhood{Id = 335, Name = "Grbe", CityId = 7},
                new Neighborhood{Id = 336, Name = "Gruda", CityId = 7},
                new Neighborhood{Id = 337, Name = "Dabojevići", CityId = 7},
                new Neighborhood{Id = 338, Name = "Daljam", CityId = 7},
                new Neighborhood{Id = 339, Name = "Do Pješivački", CityId = 7},
                new Neighborhood{Id = 340, Name = "Dolovi", CityId = 7},
                new Neighborhood{Id = 341, Name = "Donje Selo", CityId = 7},
                new Neighborhood{Id = 342, Name = "Donji Martinići", CityId = 7},
                new Neighborhood{Id = 343, Name = "Donji Rsojevići", CityId = 7},
                new Neighborhood{Id = 344, Name = "Drakovići", CityId = 7},
                new Neighborhood{Id = 345, Name = "Djedjezi", CityId = 7},
                new Neighborhood{Id = 346, Name = "Đuričkovići", CityId = 7},
                new Neighborhood{Id = 347, Name = "Župa", CityId = 7},
                new Neighborhood{Id = 348, Name = "Zagorak", CityId = 7},
                new Neighborhood{Id = 349, Name = "Zagreda", CityId = 7},
                new Neighborhood{Id = 350, Name = "Jabuke", CityId = 7},
                new Neighborhood{Id = 351, Name = "Jastreb", CityId = 7},
                new Neighborhood{Id = 352, Name = "Jelenak", CityId = 7},
                new Neighborhood{Id = 353, Name = "Jovanovići", CityId = 7},
                new Neighborhood{Id = 354, Name = "Klikovače", CityId = 7},
                new Neighborhood{Id = 355, Name = "Kopito", CityId = 7},
                new Neighborhood{Id = 356, Name = "Kosić", CityId = 7},
                new Neighborhood{Id = 357, Name = "Kujava", CityId = 7},
                new Neighborhood{Id = 358, Name = "Kupinovo", CityId = 7},
                new Neighborhood{Id = 359, Name = "Lazarev Krst", CityId = 7},
                new Neighborhood{Id = 360, Name = "Lalevići", CityId = 7},
                new Neighborhood{Id = 361, Name = "Livade", CityId = 7},
                new Neighborhood{Id = 362, Name = "Lubovo", CityId = 7},
                new Neighborhood{Id = 363, Name = "Malenza", CityId = 7},
                new Neighborhood{Id = 364, Name = "Mandići", CityId = 7},
                new Neighborhood{Id = 365, Name = "Mijokusovići", CityId = 7},
                new Neighborhood{Id = 366, Name = "Miogost", CityId = 7},
                new Neighborhood{Id = 367, Name = "Mokanje", CityId = 7},
                new Neighborhood{Id = 368, Name = "Mosori", CityId = 7},
                new Neighborhood{Id = 369, Name = "Musterovići", CityId = 7},
                new Neighborhood{Id = 370, Name = "Novo Selo", CityId = 7},
                new Neighborhood{Id = 371, Name = "Orja Luka", CityId = 7},
                new Neighborhood{Id = 372, Name = "Pitome Loze", CityId = 7},
                new Neighborhood{Id = 373, Name = "Povrhpoljina", CityId = 7},
                new Neighborhood{Id = 374, Name = "Podvraće", CityId = 7},
                new Neighborhood{Id = 375, Name = "Podglavica", CityId = 7},
                new Neighborhood{Id = 376, Name = "Požar", CityId = 7},
                new Neighborhood{Id = 377, Name = "Poljica", CityId = 7},
                new Neighborhood{Id = 378, Name = "Potkula", CityId = 7},
                new Neighborhood{Id = 379, Name = "Potočilo", CityId = 7},
                new Neighborhood{Id = 380, Name = "Ržišta", CityId = 7},
                new Neighborhood{Id = 381, Name = "Rošca", CityId = 7},
                new Neighborhood{Id = 382, Name = "Sekulići", CityId = 7},
                new Neighborhood{Id = 383, Name = "Sladojevo Kopito", CityId = 7},
                new Neighborhood{Id = 384, Name = "Slap", CityId = 7},
                new Neighborhood{Id = 385, Name = "Slatina", CityId = 7},
                new Neighborhood{Id = 386, Name = "Spuž", CityId = 7},
                new Neighborhood{Id = 387, Name = "Sretnja", CityId = 7},
                new Neighborhood{Id = 388, Name = "Strahinići", CityId = 7},
                new Neighborhood{Id = 389, Name = "Tvorilo", CityId = 7},
                new Neighborhood{Id = 390, Name = "Ćurilac", CityId = 7},
                new Neighborhood{Id = 391, Name = "Ćurčići", CityId = 7},
                new Neighborhood{Id = 392, Name = "Frutak", CityId = 7},
                new Neighborhood{Id = 393, Name = "Šobaići", CityId = 7},
                new Neighborhood{Id = 394, Name = "Šume", CityId = 7},
                new Neighborhood{Id = 395, Name = "Baošići", CityId = 8},
                new Neighborhood{Id = 396, Name = "Bijela", CityId = 8},
                new Neighborhood{Id = 397, Name = "Bijelske Kruševice", CityId = 8},
                new Neighborhood{Id = 398, Name = "Djenovići", CityId = 8},
                new Neighborhood{Id = 399, Name = "Djurići", CityId = 8},
                new Neighborhood{Id = 400, Name = "Žlijebi", CityId = 8},
                new Neighborhood{Id = 401, Name = "Zelenika", CityId = 8},
                new Neighborhood{Id = 402, Name = "Igalo", CityId = 8},
                new Neighborhood{Id = 403, Name = "Jošice", CityId = 8},
                new Neighborhood{Id = 404, Name = "Kameno", CityId = 8},
                new Neighborhood{Id = 405, Name = "Kruševice", CityId = 8},
                new Neighborhood{Id = 406, Name = "Kumbor", CityId = 8},
                new Neighborhood{Id = 407, Name = "Kuti", CityId = 8},
                new Neighborhood{Id = 408, Name = "Luštica", CityId = 8},
                new Neighborhood{Id = 409, Name = "Meljine", CityId = 8},
                new Neighborhood{Id = 410, Name = "Mojdež", CityId = 8},
                new Neighborhood{Id = 411, Name = "Mokrine", CityId = 8},
                new Neighborhood{Id = 412, Name = "Podi", CityId = 8},
                new Neighborhood{Id = 413, Name = "Prijevor", CityId = 8},
                new Neighborhood{Id = 414, Name = "Provodina", CityId = 8},
                new Neighborhood{Id = 415, Name = "Ratiševina", CityId = 8},
                new Neighborhood{Id = 416, Name = "Sasovići", CityId = 8},
                new Neighborhood{Id = 417, Name = "Sutorina", CityId = 8},
                new Neighborhood{Id = 418, Name = "Sušćepan", CityId = 8},
                new Neighborhood{Id = 419, Name = "Trebesinj", CityId = 8},
                new Neighborhood{Id = 420, Name = "Ubli", CityId = 8},
                new Neighborhood{Id = 421, Name = "Babljak", CityId = 9},
                new Neighborhood{Id = 422, Name = "Bakovići", CityId = 9},
                new Neighborhood{Id = 423, Name = "Bare", CityId = 9},
                new Neighborhood{Id = 424, Name = "Lipovska Bistrica", CityId = 9},
                new Neighborhood{Id = 425, Name = "Moračka Bistrica", CityId = 9},
                new Neighborhood{Id = 426, Name = "Blatina", CityId = 9},
                new Neighborhood{Id = 427, Name = "Bojići", CityId = 9},
                new Neighborhood{Id = 428, Name = "Breza", CityId = 9},
                new Neighborhood{Id = 429, Name = "Gornja Rovca Bulatovići", CityId = 9},
                new Neighborhood{Id = 430, Name = "Velje Duboko", CityId = 9},
                new Neighborhood{Id = 431, Name = "Višnje", CityId = 9},
                new Neighborhood{Id = 432, Name = "Vladoš", CityId = 9},
                new Neighborhood{Id = 433, Name = "Vlahovići", CityId = 9},
                new Neighborhood{Id = 434, Name = "Vojkovići", CityId = 9},
                new Neighborhood{Id = 435, Name = "Vranještica", CityId = 9},
                new Neighborhood{Id = 436, Name = "Vrujica", CityId = 9},
                new Neighborhood{Id = 437, Name = "Gornje Lipovo", CityId = 9},
                new Neighborhood{Id = 438, Name = "Donje Lipovo", CityId = 9},
                new Neighborhood{Id = 439, Name = "Dragovića Polje", CityId = 9},
                new Neighborhood{Id = 440, Name = "Drijenak", CityId = 9},
                new Neighborhood{Id = 441, Name = "Drpe", CityId = 9},
                new Neighborhood{Id = 442, Name = "Dulovine", CityId = 9},
                new Neighborhood{Id = 443, Name = "Djudjevina", CityId = 9},
                new Neighborhood{Id = 444, Name = "Žirci", CityId = 9},
                new Neighborhood{Id = 445, Name = "Izlasci", CityId = 9},
                new Neighborhood{Id = 446, Name = "Jabuka", CityId = 9},
                new Neighborhood{Id = 447, Name = "Jasenova", CityId = 9},
                new Neighborhood{Id = 448, Name = "Kos", CityId = 9},
                new Neighborhood{Id = 449, Name = "Bare Kraljske", CityId = 9},
                new Neighborhood{Id = 450, Name = "Ljevišta", CityId = 9},
                new Neighborhood{Id = 451, Name = "Liješnje", CityId = 9},
                new Neighborhood{Id = 452, Name = "Ljuta", CityId = 9},
                new Neighborhood{Id = 453, Name = "Mateševo", CityId = 9},
                new Neighborhood{Id = 454, Name = "Medjuriječje", CityId = 9},
                new Neighborhood{Id = 455, Name = "Mioska", CityId = 9},
                new Neighborhood{Id = 456, Name = "Moračko Trebaljevo", CityId = 9},
                new Neighborhood{Id = 457, Name = "Mujića Rečine", CityId = 9},
                new Neighborhood{Id = 458, Name = "Mušovića Rijeka", CityId = 9},
                new Neighborhood{Id = 459, Name = "Osretci", CityId = 9},
                new Neighborhood{Id = 460, Name = "Oćiba", CityId = 9},
                new Neighborhood{Id = 461, Name = "Padež", CityId = 9},
                new Neighborhood{Id = 462, Name = "Petrova Ravan", CityId = 9},
                new Neighborhood{Id = 463, Name = "Plana", CityId = 9},
                new Neighborhood{Id = 464, Name = "Ulica", CityId = 9},
                new Neighborhood{Id = 465, Name = "Požnja", CityId = 9},
                new Neighborhood{Id = 466, Name = "Pčinja", CityId = 9},
                new Neighborhood{Id = 467, Name = "Ravni", CityId = 9},
                new Neighborhood{Id = 468, Name = "Raško", CityId = 9},
                new Neighborhood{Id = 469, Name = "Radigojno", CityId = 9},
                new Neighborhood{Id = 470, Name = "Redice", CityId = 9},
                new Neighborhood{Id = 471, Name = "Rovačko Trebaljevo", CityId = 9},
                new Neighborhood{Id = 472, Name = "Svrke", CityId = 9},
                new Neighborhood{Id = 473, Name = "Sela", CityId = 9},
                new Neighborhood{Id = 474, Name = "Selišta", CityId = 9},
                new Neighborhood{Id = 475, Name = "Sjerogošte", CityId = 9},
                new Neighborhood{Id = 476, Name = "Skrbuša", CityId = 9},
                new Neighborhood{Id = 477, Name = "Smailagića Polje", CityId = 9},
                new Neighborhood{Id = 478, Name = "Smrče", CityId = 9},
                new Neighborhood{Id = 479, Name = "Sreteška Gora", CityId = 9},
                new Neighborhood{Id = 480, Name = "Starče", CityId = 9},
                new Neighborhood{Id = 481, Name = "Tara", CityId = 9},
                new Neighborhood{Id = 482, Name = "Trnovica", CityId = 9},
                new Neighborhood{Id = 483, Name = "Uvač", CityId = 9},
                new Neighborhood{Id = 484, Name = "Cerovice", CityId = 9},
                new Neighborhood{Id = 485, Name = "Crkvine", CityId = 9},
                new Neighborhood{Id = 486, Name = "Manastir Morača", CityId = 9},
                new Neighborhood{Id = 487, Name = "Mrtvo Duboko", CityId = 9},
                new Neighborhood{Id = 488, Name = "Ocka Gora", CityId = 9},
                new Neighborhood{Id = 489, Name = "Raičevina", CityId = 9},
                new Neighborhood{Id = 490, Name = "Bratešići", CityId = 10},
                new Neighborhood{Id = 491, Name = "Veliki Zalazi", CityId = 10},
                new Neighborhood{Id = 492, Name = "Višnjeva", CityId = 10},
                new Neighborhood{Id = 493, Name = "Vranovići", CityId = 10},
                new Neighborhood{Id = 494, Name = "Glavati", CityId = 10},
                new Neighborhood{Id = 495, Name = "Glavatičići", CityId = 10},
                new Neighborhood{Id = 496, Name = "Gornji Morinj", CityId = 10},
                new Neighborhood{Id = 497, Name = "Gornji Orahovac", CityId = 10},
                new Neighborhood{Id = 498, Name = "Gornji Stoliv", CityId = 10},
                new Neighborhood{Id = 499, Name = "Gorovići", CityId = 10},
                new Neighborhood{Id = 500, Name = "Dobrota", CityId = 10},
                new Neighborhood{Id = 501, Name = "Donji Morinj", CityId = 10},
                new Neighborhood{Id = 502, Name = "Donji Orahovac", CityId = 10},
                new Neighborhood{Id = 503, Name = "Donji Stoliv", CityId = 10},
                new Neighborhood{Id = 504, Name = "Dragalj", CityId = 10},
                new Neighborhood{Id = 505, Name = "Dub", CityId = 10},
                new Neighborhood{Id = 506, Name = "Zagora", CityId = 10},
                new Neighborhood{Id = 507, Name = "Zvečava", CityId = 10},
                new Neighborhood{Id = 508, Name = "Kavač", CityId = 10},
                new Neighborhood{Id = 509, Name = "Knežlaz", CityId = 10},
                new Neighborhood{Id = 510, Name = "Kovači", CityId = 10},
                new Neighborhood{Id = 511, Name = "Kostanjica", CityId = 10},
                new Neighborhood{Id = 512, Name = "Krimovica", CityId = 10},
                new Neighborhood{Id = 513, Name = "Kubasi", CityId = 10},
                new Neighborhood{Id = 514, Name = "Lastva Grbaljska", CityId = 10},
                new Neighborhood{Id = 515, Name = "Ledenice", CityId = 10},
                new Neighborhood{Id = 516, Name = "Lješevići", CityId = 10},
                new Neighborhood{Id = 517, Name = "Mali Zalazi", CityId = 10},
                new Neighborhood{Id = 518, Name = "Malov Do", CityId = 10},
                new Neighborhood{Id = 519, Name = "Mirac", CityId = 10},
                new Neighborhood{Id = 520, Name = "Muo", CityId = 10},
                new Neighborhood{Id = 521, Name = "Nalježići", CityId = 10},
                new Neighborhood{Id = 522, Name = "Pelinovo", CityId = 10},
                new Neighborhood{Id = 523, Name = "Perast", CityId = 10},
                new Neighborhood{Id = 524, Name = "Pištet", CityId = 10},
                new Neighborhood{Id = 525, Name = "Pobrdje", CityId = 10},
                new Neighborhood{Id = 526, Name = "Prijeradi", CityId = 10},
                new Neighborhood{Id = 527, Name = "Prčanj", CityId = 10},
                new Neighborhood{Id = 528, Name = "Radanovići", CityId = 10},
                new Neighborhood{Id = 529, Name = "Risan", CityId = 10},
                new Neighborhood{Id = 530, Name = "Strp", CityId = 10},
                new Neighborhood{Id = 531, Name = "Sutvara", CityId = 10},
                new Neighborhood{Id = 532, Name = "Han", CityId = 10},
                new Neighborhood{Id = 533, Name = "Čavori", CityId = 10},
                new Neighborhood{Id = 534, Name = "Šišići", CityId = 10},
                new Neighborhood{Id = 535, Name = "Bigova", CityId = 10},
                new Neighborhood{Id = 536, Name = "Bunovići", CityId = 10},
                new Neighborhood{Id = 537, Name = "Dražin Vrt", CityId = 10},
                new Neighborhood{Id = 538, Name = "Kolužunj", CityId = 10},
                new Neighborhood{Id = 539, Name = "Trešnjica", CityId = 10},
                new Neighborhood{Id = 540, Name = "Ukropci", CityId = 10},
                new Neighborhood{Id = 541, Name = "Lipci", CityId = 10},
                new Neighborhood{Id = 542, Name = "Unijerina", CityId = 10},
                new Neighborhood{Id = 543, Name = "Špiljari", CityId = 10},
                new Neighborhood{Id = 544, Name = "Škaljari", CityId = 10},
                new Neighborhood{Id = 545, Name = "Bistrica", CityId = 11},
                new Neighborhood{Id = 546, Name = "Gojakovići", CityId = 11},
                new Neighborhood{Id = 547, Name = "Dobrilovina", CityId = 11},
                new Neighborhood{Id = 548, Name = "Žari", CityId = 11},
                new Neighborhood{Id = 549, Name = "Lepenac", CityId = 11},
                new Neighborhood{Id = 550, Name = "Podbišće", CityId = 11},
                new Neighborhood{Id = 551, Name = "Stevanovac", CityId = 11},
                new Neighborhood{Id = 552, Name = "Štitarica", CityId = 11},
                new Neighborhood{Id = 553, Name = "Bjelojevići", CityId = 11},
                new Neighborhood{Id = 554, Name = "Bojna Njiva", CityId = 11},
                new Neighborhood{Id = 555, Name = "Brskovo", CityId = 11},
                new Neighborhood{Id = 556, Name = "Prošćenje", CityId = 11},
                new Neighborhood{Id = 557, Name = "Uroševina", CityId = 11},
                new Neighborhood{Id = 558, Name = "Polja", CityId = 11},
                new Neighborhood{Id = 559, Name = "Balosave", CityId = 12},
                new Neighborhood{Id = 560, Name = "Bare", CityId = 12},
                new Neighborhood{Id = 561, Name = "Bastaji", CityId = 12},
                new Neighborhood{Id = 562, Name = "Bjeloševina", CityId = 12},
                new Neighborhood{Id = 563, Name = "Bobotovo Groblje", CityId = 12},
                new Neighborhood{Id = 564, Name = "Bogetići", CityId = 12},
                new Neighborhood{Id = 565, Name = "Bogmilovići", CityId = 12},
                new Neighborhood{Id = 566, Name = "Brezovik", CityId = 12},
                new Neighborhood{Id = 567, Name = "Brestice", CityId = 12},
                new Neighborhood{Id = 568, Name = "Broćanac Viluški", CityId = 12},
                new Neighborhood{Id = 569, Name = "Broćanac Nikšićki", CityId = 12},
                new Neighborhood{Id = 570, Name = "Bršno", CityId = 12},
                new Neighborhood{Id = 571, Name = "Bubrežak", CityId = 12},
                new Neighborhood{Id = 572, Name = "Busak", CityId = 12},
                new Neighborhood{Id = 573, Name = "Vasiljevići", CityId = 12},
                new Neighborhood{Id = 574, Name = "Velimlje", CityId = 12},
                new Neighborhood{Id = 575, Name = "Vidne", CityId = 12},
                new Neighborhood{Id = 576, Name = "Vilusi", CityId = 12},
                new Neighborhood{Id = 577, Name = "Vir", CityId = 12},
                new Neighborhood{Id = 578, Name = "Vitasojevići", CityId = 12},
                new Neighborhood{Id = 579, Name = "Višnjića Do", CityId = 12},
                new Neighborhood{Id = 580, Name = "Vraćenovići", CityId = 12},
                new Neighborhood{Id = 581, Name = "Vrbica", CityId = 12},
                new Neighborhood{Id = 582, Name = "Vučji Do", CityId = 12},
                new Neighborhood{Id = 583, Name = "Gvozd", CityId = 12},
                new Neighborhood{Id = 584, Name = "Gornja Trepča", CityId = 12},
                new Neighborhood{Id = 585, Name = "Gornje Polje", CityId = 12},
                new Neighborhood{Id = 586, Name = "Gornje Crkvice", CityId = 12},
                new Neighborhood{Id = 587, Name = "Gornje Čarađe", CityId = 12},
                new Neighborhood{Id = 588, Name = "Goslić", CityId = 12},
                new Neighborhood{Id = 589, Name = "Gradačka Poljana", CityId = 12},
                new Neighborhood{Id = 590, Name = "Granice", CityId = 12},
                new Neighborhood{Id = 591, Name = "Grahovac", CityId = 12},
                new Neighborhood{Id = 592, Name = "Grahovo", CityId = 12},
                new Neighborhood{Id = 593, Name = "Dolovi", CityId = 12},
                new Neighborhood{Id = 594, Name = "Donja Trepča", CityId = 12},
                new Neighborhood{Id = 595, Name = "Donje Crkvice", CityId = 12},
                new Neighborhood{Id = 596, Name = "Donje Čaradje", CityId = 12},
                new Neighborhood{Id = 597, Name = "Dragovoljići", CityId = 12},
                new Neighborhood{Id = 598, Name = "Drenoštica", CityId = 12},
                new Neighborhood{Id = 599, Name = "Dubočke", CityId = 12},
                new Neighborhood{Id = 600, Name = "Duga", CityId = 12},
                new Neighborhood{Id = 601, Name = "Dučice", CityId = 12},
                new Neighborhood{Id = 602, Name = "Zavrh", CityId = 12},
                new Neighborhood{Id = 603, Name = "Zagora", CityId = 12},
                new Neighborhood{Id = 604, Name = "Zagrad", CityId = 12},
                new Neighborhood{Id = 605, Name = "Zaljutnica", CityId = 12},
                new Neighborhood{Id = 606, Name = "Zaslap", CityId = 12},
                new Neighborhood{Id = 607, Name = "Zlostup", CityId = 12},
                new Neighborhood{Id = 608, Name = "Ivanje", CityId = 12},
                new Neighborhood{Id = 609, Name = "Jabuke", CityId = 12},
                new Neighborhood{Id = 610, Name = "Javljem", CityId = 12},
                new Neighborhood{Id = 611, Name = "Jasenovo Polje", CityId = 12},
                new Neighborhood{Id = 612, Name = "Jugovići", CityId = 12},
                new Neighborhood{Id = 613, Name = "Kazanci", CityId = 12},
                new Neighborhood{Id = 614, Name = "Kamensko", CityId = 12},
                new Neighborhood{Id = 615, Name = "Klenak", CityId = 12},
                new Neighborhood{Id = 616, Name = "Kovači", CityId = 12},
                new Neighborhood{Id = 617, Name = "Koprivice", CityId = 12},
                new Neighborhood{Id = 618, Name = "Koravlica", CityId = 12},
                new Neighborhood{Id = 619, Name = "Kunak", CityId = 12},
                new Neighborhood{Id = 620, Name = "Kuside", CityId = 12},
                new Neighborhood{Id = 621, Name = "Kuta", CityId = 12},
                new Neighborhood{Id = 622, Name = "Laz", CityId = 12},
                new Neighborhood{Id = 623, Name = "Liverovići", CityId = 12},
                new Neighborhood{Id = 624, Name = "Lukovo", CityId = 12},
                new Neighborhood{Id = 625, Name = "Macavare", CityId = 12},
                new Neighborhood{Id = 626, Name = "Medjedje", CityId = 12},
                new Neighborhood{Id = 627, Name = "Milojevići", CityId = 12},
                new Neighborhood{Id = 628, Name = "Miločani", CityId = 12},
                new Neighborhood{Id = 629, Name = "Miljanići", CityId = 12},
                new Neighborhood{Id = 630, Name = "Miruše", CityId = 12},
                new Neighborhood{Id = 631, Name = "Mokri Do", CityId = 12},
                new Neighborhood{Id = 632, Name = "Morakovo", CityId = 12},
                new Neighborhood{Id = 633, Name = "Nudo", CityId = 12},
                new Neighborhood{Id = 634, Name = "Oblatno", CityId = 12},
                new Neighborhood{Id = 635, Name = "Ozrinići", CityId = 12},
                new Neighborhood{Id = 636, Name = "Orah", CityId = 12},
                new Neighborhood{Id = 637, Name = "Orlina", CityId = 12},
                new Neighborhood{Id = 638, Name = "Petrovići", CityId = 12},
                new Neighborhood{Id = 639, Name = "Pilatovci", CityId = 12},
                new Neighborhood{Id = 640, Name = "Povija", CityId = 12},
                new Neighborhood{Id = 641, Name = "Podbožur", CityId = 12},
                new Neighborhood{Id = 642, Name = "Podvrš", CityId = 12},
                new Neighborhood{Id = 643, Name = "Ponikvica", CityId = 12},
                new Neighborhood{Id = 644, Name = "Počekovići", CityId = 12},
                new Neighborhood{Id = 645, Name = "Praga", CityId = 12},
                new Neighborhood{Id = 646, Name = "Prigradina", CityId = 12},
                new Neighborhood{Id = 647, Name = "Prisoje", CityId = 12},
                new Neighborhood{Id = 648, Name = "Rastovac", CityId = 12},
                new Neighborhood{Id = 649, Name = "Riđani", CityId = 12},
                new Neighborhood{Id = 650, Name = "Riječani", CityId = 12},
                new Neighborhood{Id = 651, Name = "Rudine", CityId = 12},
                new Neighborhood{Id = 652, Name = "Sjenokosi", CityId = 12},
                new Neighborhood{Id = 653, Name = "Smrduša", CityId = 12},
                new Neighborhood{Id = 654, Name = "Somina", CityId = 12},
                new Neighborhood{Id = 655, Name = "Spila", CityId = 12},
                new Neighborhood{Id = 656, Name = "Srijede", CityId = 12},
                new Neighborhood{Id = 657, Name = "Staro Selo", CityId = 12},
                new Neighborhood{Id = 658, Name = "Stuba", CityId = 12},
                new Neighborhood{Id = 659, Name = "Stubica", CityId = 12},
                new Neighborhood{Id = 660, Name = "Tupan", CityId = 12},
                new Neighborhood{Id = 661, Name = "Ubli", CityId = 12},
                new Neighborhood{Id = 662, Name = "Carine", CityId = 12},
                new Neighborhood{Id = 663, Name = "Cerovo", CityId = 12},
                new Neighborhood{Id = 664, Name = "Crnodoli", CityId = 12},
                new Neighborhood{Id = 665, Name = "Šipačno", CityId = 12},
                new Neighborhood{Id = 666, Name = "Štedim", CityId = 12},
                new Neighborhood{Id = 667, Name = "Štitari", CityId = 12},
                new Neighborhood{Id = 668, Name = "Bogajići", CityId = 13},
                new Neighborhood{Id = 669, Name = "Brezojevica", CityId = 13},
                new Neighborhood{Id = 670, Name = "Velika", CityId = 13},
                new Neighborhood{Id = 671, Name = "Višnjevo", CityId = 13},
                new Neighborhood{Id = 672, Name = "Vojno Selo", CityId = 13},
                new Neighborhood{Id = 673, Name = "Vusanje", CityId = 13},
                new Neighborhood{Id = 674, Name = "Gornja Rženica", CityId = 13},
                new Neighborhood{Id = 675, Name = "Grnčar", CityId = 13},
                new Neighborhood{Id = 676, Name = "Gusinje", CityId = 13},
                new Neighborhood{Id = 677, Name = "Dolja", CityId = 13},
                new Neighborhood{Id = 678, Name = "Dosudje", CityId = 13},
                new Neighborhood{Id = 679, Name = "Djurička Rijeka", CityId = 13},
                new Neighborhood{Id = 680, Name = "Kolenovići", CityId = 13},
                new Neighborhood{Id = 681, Name = "Kruševo", CityId = 13},
                new Neighborhood{Id = 682, Name = "Martinovići", CityId = 13},
                new Neighborhood{Id = 683, Name = "Mašnica", CityId = 13},
                new Neighborhood{Id = 684, Name = "Meteh", CityId = 13},
                new Neighborhood{Id = 685, Name = "Murino", CityId = 13},
                new Neighborhood{Id = 686, Name = "Novšići", CityId = 13},
                new Neighborhood{Id = 687, Name = "Prnjavor", CityId = 13},
                new Neighborhood{Id = 688, Name = "Skić", CityId = 13},
                new Neighborhood{Id = 689, Name = "Hoti", CityId = 13},
                new Neighborhood{Id = 690, Name = "Alići", CityId = 14},
                new Neighborhood{Id = 691, Name = "Boščinovići", CityId = 14},
                new Neighborhood{Id = 692, Name = "Beljkovići", CityId = 14},
                new Neighborhood{Id = 693, Name = "Bjeloševina", CityId = 14},
                new Neighborhood{Id = 694, Name = "Bobovo", CityId = 14},
                new Neighborhood{Id = 695, Name = "Boljanići", CityId = 14},
                new Neighborhood{Id = 696, Name = "Borišići", CityId = 14},
                new Neighborhood{Id = 697, Name = "Borova", CityId = 14},
                new Neighborhood{Id = 698, Name = "Borovica", CityId = 14},
                new Neighborhood{Id = 699, Name = "Brda", CityId = 14},
                new Neighborhood{Id = 700, Name = "Bujaci", CityId = 14},
                new Neighborhood{Id = 701, Name = "Burići", CityId = 14},
                new Neighborhood{Id = 702, Name = "Bušnje", CityId = 14},
                new Neighborhood{Id = 703, Name = "Varine", CityId = 14},
                new Neighborhood{Id = 704, Name = "Vaškovo", CityId = 14},
                new Neighborhood{Id = 705, Name = "Velike Krće", CityId = 14},
                new Neighborhood{Id = 706, Name = "Vidre", CityId = 14},
                new Neighborhood{Id = 707, Name = "Vijenac", CityId = 14},
                new Neighborhood{Id = 708, Name = "Vilići", CityId = 14},
                new Neighborhood{Id = 709, Name = "Višnjica", CityId = 14},
                new Neighborhood{Id = 710, Name = "Vodno", CityId = 14},
                new Neighborhood{Id = 711, Name = "Vojtina", CityId = 14},
                new Neighborhood{Id = 712, Name = "Vrba", CityId = 14},
                new Neighborhood{Id = 713, Name = "Vrbica", CityId = 14},
                new Neighborhood{Id = 714, Name = "Vrulja", CityId = 14},
                new Neighborhood{Id = 715, Name = "Vukšići", CityId = 14},
                new Neighborhood{Id = 716, Name = "Geuši", CityId = 14},
                new Neighborhood{Id = 717, Name = "Glibaći", CityId = 14},
                new Neighborhood{Id = 718, Name = "Glisnica", CityId = 14},
                new Neighborhood{Id = 719, Name = "Gornja Brvenica", CityId = 14},
                new Neighborhood{Id = 720, Name = "Gornje Selo", CityId = 14},
                new Neighborhood{Id = 721, Name = "Gotovuša", CityId = 14},
                new Neighborhood{Id = 722, Name = "Gradac", CityId = 14},
                new Neighborhood{Id = 723, Name = "Gradina", CityId = 14},
                new Neighborhood{Id = 724, Name = "Grevo", CityId = 14},
                new Neighborhood{Id = 725, Name = "Donja Brvenica", CityId = 14},
                new Neighborhood{Id = 726, Name = "Dragaši", CityId = 14},
                new Neighborhood{Id = 727, Name = "Dubac", CityId = 14},
                new Neighborhood{Id = 728, Name = "Dubočica", CityId = 14},
                new Neighborhood{Id = 729, Name = "Dubrava", CityId = 14},
                new Neighborhood{Id = 730, Name = "Dužice", CityId = 14},
                new Neighborhood{Id = 731, Name = "Durutovići", CityId = 14},
                new Neighborhood{Id = 732, Name = "Đuli", CityId = 14},
                new Neighborhood{Id = 733, Name = "Đurđevića Tara", CityId = 14},
                new Neighborhood{Id = 734, Name = "Židovići", CityId = 14},
                new Neighborhood{Id = 735, Name = "Zabrđe", CityId = 14},
                new Neighborhood{Id = 736, Name = "Zaselje", CityId = 14},
                new Neighborhood{Id = 737, Name = "Zbljevo", CityId = 14},
                new Neighborhood{Id = 738, Name = "Zekavice", CityId = 14},
                new Neighborhood{Id = 739, Name = "Zenica", CityId = 14},
                new Neighborhood{Id = 740, Name = "Zorlovići", CityId = 14},
                new Neighborhood{Id = 741, Name = "Jabuka", CityId = 14},
                new Neighborhood{Id = 742, Name = "Jagodni Do", CityId = 14},
                new Neighborhood{Id = 743, Name = "Jasen", CityId = 14},
                new Neighborhood{Id = 744, Name = "Jahovići", CityId = 14},
                new Neighborhood{Id = 745, Name = "Jugovo", CityId = 14},
                new Neighborhood{Id = 746, Name = "Kakmuži", CityId = 14},
                new Neighborhood{Id = 747, Name = "Kalušići", CityId = 14},
                new Neighborhood{Id = 748, Name = "Katun", CityId = 14},
                new Neighborhood{Id = 749, Name = "Klakorina", CityId = 14},
                new Neighborhood{Id = 750, Name = "Kovači", CityId = 14},
                new Neighborhood{Id = 751, Name = "Kovačevići", CityId = 14},
                new Neighborhood{Id = 752, Name = "Kozica", CityId = 14},
                new Neighborhood{Id = 753, Name = "Komine", CityId = 14},
                new Neighborhood{Id = 754, Name = "Kordovina", CityId = 14},
                new Neighborhood{Id = 755, Name = "Kosanica", CityId = 14},
                new Neighborhood{Id = 756, Name = "Kotlajići", CityId = 14},
                new Neighborhood{Id = 757, Name = "Kotline", CityId = 14},
                new Neighborhood{Id = 758, Name = "Kotorac", CityId = 14},
                new Neighborhood{Id = 759, Name = "Košare", CityId = 14},
                new Neighborhood{Id = 760, Name = "Kržava", CityId = 14},
                new Neighborhood{Id = 761, Name = "Krćevina", CityId = 14},
                new Neighborhood{Id = 762, Name = "Krupice", CityId = 14},
                new Neighborhood{Id = 763, Name = "Kruševo", CityId = 14},
                new Neighborhood{Id = 764, Name = "Kukavica", CityId = 14},
                new Neighborhood{Id = 765, Name = "Ladjana", CityId = 14},
                new Neighborhood{Id = 766, Name = "Lever Tara", CityId = 14},
                new Neighborhood{Id = 767, Name = "Leovo Brdo", CityId = 14},
                new Neighborhood{Id = 768, Name = "Lijeska", CityId = 14},
                new Neighborhood{Id = 769, Name = "Lugovi", CityId = 14},
                new Neighborhood{Id = 770, Name = "Ljutići", CityId = 14},
                new Neighborhood{Id = 771, Name = "Ljuće", CityId = 14},
                new Neighborhood{Id = 772, Name = "Male Krće", CityId = 14},
                new Neighborhood{Id = 773, Name = "Maoče", CityId = 14},
                new Neighborhood{Id = 774, Name = "Mataruge", CityId = 14},
                new Neighborhood{Id = 775, Name = "Madžari", CityId = 14},
                new Neighborhood{Id = 776, Name = "Meljak", CityId = 14},
                new Neighborhood{Id = 777, Name = "Metaljka", CityId = 14},
                new Neighborhood{Id = 778, Name = "Mijakovići", CityId = 14},
                new Neighborhood{Id = 779, Name = "Milakovići", CityId = 14},
                new Neighborhood{Id = 780, Name = "Milunići", CityId = 14},
                new Neighborhood{Id = 781, Name = "Mironići", CityId = 14},
                new Neighborhood{Id = 782, Name = "Moraice", CityId = 14},
                new Neighborhood{Id = 783, Name = "Moćevići", CityId = 14},
                new Neighborhood{Id = 784, Name = "Mrzovići", CityId = 14},
                new Neighborhood{Id = 785, Name = "Mrčevo", CityId = 14},
                new Neighborhood{Id = 786, Name = "Mrčići", CityId = 14},
                new Neighborhood{Id = 787, Name = "Nange", CityId = 14},
                new Neighborhood{Id = 788, Name = "Obarde", CityId = 14},
                new Neighborhood{Id = 789, Name = "Ogradjenica", CityId = 14},
                new Neighborhood{Id = 790, Name = "Orlja", CityId = 14},
                new Neighborhood{Id = 791, Name = "Otilovići", CityId = 14},
                new Neighborhood{Id = 792, Name = "Odžak", CityId = 14},
                new Neighborhood{Id = 793, Name = "Petine", CityId = 14},
                new Neighborhood{Id = 794, Name = "Pauče", CityId = 14},
                new Neighborhood{Id = 795, Name = "Pižure", CityId = 14},
                new Neighborhood{Id = 796, Name = "Plakala", CityId = 14},
                new Neighborhood{Id = 797, Name = "Planjsko", CityId = 14},
                new Neighborhood{Id = 798, Name = "Pliješevina", CityId = 14},
                new Neighborhood{Id = 799, Name = "Pliješ", CityId = 14},
                new Neighborhood{Id = 800, Name = "Poblaće", CityId = 14},
                new Neighborhood{Id = 801, Name = "Podborova", CityId = 14},
                new Neighborhood{Id = 802, Name = "Popov Do", CityId = 14},
                new Neighborhood{Id = 803, Name = "Potkovač", CityId = 14},
                new Neighborhood{Id = 804, Name = "Potkrajci", CityId = 14},
                new Neighborhood{Id = 805, Name = "Potoci", CityId = 14},
                new Neighborhood{Id = 806, Name = "Potpeće", CityId = 14},
                new Neighborhood{Id = 807, Name = "Potrlica", CityId = 14},
                new Neighborhood{Id = 808, Name = "Pračica", CityId = 14},
                new Neighborhood{Id = 809, Name = "Premćani", CityId = 14},
                new Neighborhood{Id = 810, Name = "Prehari", CityId = 14},
                new Neighborhood{Id = 811, Name = "Prisoji", CityId = 14},
                new Neighborhood{Id = 812, Name = "Prošće", CityId = 14},
                new Neighborhood{Id = 813, Name = "Pušanjski Do", CityId = 14},
                new Neighborhood{Id = 814, Name = "Rabitlje", CityId = 14},
                new Neighborhood{Id = 815, Name = "Rađevići", CityId = 14},
                new Neighborhood{Id = 816, Name = "Romač", CityId = 14},
                new Neighborhood{Id = 817, Name = "Rudnica", CityId = 14},
                new Neighborhood{Id = 818, Name = "Rujevica", CityId = 14},
                new Neighborhood{Id = 819, Name = "Selac", CityId = 14},
                new Neighborhood{Id = 820, Name = "Selišta", CityId = 14},
                new Neighborhood{Id = 821, Name = "Sirčići", CityId = 14},
                new Neighborhood{Id = 822, Name = "Slatina", CityId = 14},
                new Neighborhood{Id = 823, Name = "Srećanje", CityId = 14},
                new Neighborhood{Id = 824, Name = "Stančani", CityId = 14},
                new Neighborhood{Id = 825, Name = "Stranice", CityId = 14},
                new Neighborhood{Id = 826, Name = "Strahov Do", CityId = 14},
                new Neighborhood{Id = 827, Name = "Tvrdakovići", CityId = 14},
                new Neighborhood{Id = 828, Name = "Trnovice", CityId = 14},
                new Neighborhood{Id = 829, Name = "Uremovići", CityId = 14},
                new Neighborhood{Id = 830, Name = "Horevina", CityId = 14},
                new Neighborhood{Id = 831, Name = "Hoćevina", CityId = 14},
                new Neighborhood{Id = 832, Name = "Cerovci", CityId = 14},
                new Neighborhood{Id = 833, Name = "Crljenice", CityId = 14},
                new Neighborhood{Id = 834, Name = "Crni Vrh", CityId = 14},
                new Neighborhood{Id = 835, Name = "Crno Brdo", CityId = 14},
                new Neighborhood{Id = 836, Name = "Crnobori", CityId = 14},
                new Neighborhood{Id = 837, Name = "Čavanj", CityId = 14},
                new Neighborhood{Id = 838, Name = "Čardak", CityId = 14},
                new Neighborhood{Id = 839, Name = "Čerjenci", CityId = 14},
                new Neighborhood{Id = 840, Name = "Čestin", CityId = 14},
                new Neighborhood{Id = 841, Name = "Šljivansko", CityId = 14},
                new Neighborhood{Id = 842, Name = "Šljuke", CityId = 14},
                new Neighborhood{Id = 843, Name = "Šula", CityId = 14},
                new Neighborhood{Id = 844, Name = "Šumani", CityId = 14},
                new Neighborhood{Id = 845, Name = "Paljevine", CityId = 14},
                new Neighborhood{Id = 846, Name = "Kolijevka", CityId = 14},
                new Neighborhood{Id = 847, Name = "Tatarovina", CityId = 14},
                new Neighborhood{Id = 848, Name = "Babići", CityId = 15},
                new Neighborhood{Id = 849, Name = "Bajovo Polje", CityId = 15},
                new Neighborhood{Id = 850, Name = "Barni Do", CityId = 15},
                new Neighborhood{Id = 851, Name = "Bezuje", CityId = 15},
                new Neighborhood{Id = 852, Name = "Bojati", CityId = 15},
                new Neighborhood{Id = 853, Name = "Boričje", CityId = 15},
                new Neighborhood{Id = 854, Name = "Borkovići", CityId = 15},
                new Neighborhood{Id = 855, Name = "Brijeg", CityId = 15},
                new Neighborhood{Id = 856, Name = "Brljevo", CityId = 15},
                new Neighborhood{Id = 857, Name = "Bukovac", CityId = 15},
                new Neighborhood{Id = 858, Name = "Vojinovići", CityId = 15},
                new Neighborhood{Id = 859, Name = "Goransko", CityId = 15},
                new Neighborhood{Id = 860, Name = "Gornja Brezna", CityId = 15},
                new Neighborhood{Id = 861, Name = "Donja Brezna", CityId = 15},
                new Neighborhood{Id = 862, Name = "Dubljevići", CityId = 15},
                new Neighborhood{Id = 863, Name = "Žeično", CityId = 15},
                new Neighborhood{Id = 864, Name = "Zabrdje", CityId = 15},
                new Neighborhood{Id = 865, Name = "Zukva", CityId = 15},
                new Neighborhood{Id = 866, Name = "Jerinići", CityId = 15},
                new Neighborhood{Id = 867, Name = "Kneževići", CityId = 15},
                new Neighborhood{Id = 868, Name = "Kovači", CityId = 15},
                new Neighborhood{Id = 869, Name = "Lisina", CityId = 15},
                new Neighborhood{Id = 870, Name = "Miloševići", CityId = 15},
                new Neighborhood{Id = 871, Name = "Miljkovac", CityId = 15},
                new Neighborhood{Id = 872, Name = "Mratinje", CityId = 15},
                new Neighborhood{Id = 873, Name = "Nedajno", CityId = 15},
                new Neighborhood{Id = 874, Name = "Nikovići", CityId = 15},
                new Neighborhood{Id = 875, Name = "Osojni Orah", CityId = 15},
                new Neighborhood{Id = 876, Name = "Pišče", CityId = 15},
                new Neighborhood{Id = 877, Name = "Poljana", CityId = 15},
                new Neighborhood{Id = 878, Name = "Crkvičko Polje", CityId = 15},
                new Neighborhood{Id = 879, Name = "Prisojni Orah", CityId = 15},
                new Neighborhood{Id = 880, Name = "Ravno", CityId = 15},
                new Neighborhood{Id = 881, Name = "Rudinice", CityId = 15},
                new Neighborhood{Id = 882, Name = "Seljani", CityId = 15},
                new Neighborhood{Id = 883, Name = "Smriječno", CityId = 15},
                new Neighborhood{Id = 884, Name = "Stabna", CityId = 15},
                new Neighborhood{Id = 885, Name = "Stolac", CityId = 15},
                new Neighborhood{Id = 886, Name = "Stubica", CityId = 15},
                new Neighborhood{Id = 887, Name = "Trsa", CityId = 15},
                new Neighborhood{Id = 888, Name = "Unač", CityId = 15},
                new Neighborhood{Id = 889, Name = "Šarići", CityId = 15},
                new Neighborhood{Id = 890, Name = "Arza", CityId = 16},
                new Neighborhood{Id = 891, Name = "Balabani", CityId = 16},
                new Neighborhood{Id = 892, Name = "Baloči", CityId = 16},
                new Neighborhood{Id = 893, Name = "Barlaj", CityId = 16},
                new Neighborhood{Id = 894, Name = "Begova Glavica", CityId = 16},
                new Neighborhood{Id = 895, Name = "Bezjovo", CityId = 16},
                new Neighborhood{Id = 896, Name = "Benkaj", CityId = 16},
                new Neighborhood{Id = 897, Name = "Beri", CityId = 16},
                new Neighborhood{Id = 898, Name = "Berislavci", CityId = 16},
                new Neighborhood{Id = 899, Name = "Bigor", CityId = 16},
                new Neighborhood{Id = 900, Name = "Bioče", CityId = 16},
                new Neighborhood{Id = 901, Name = "Bistrice", CityId = 16},
                new Neighborhood{Id = 902, Name = "Blizna", CityId = 16},
                new Neighborhood{Id = 903, Name = "Bolesestra", CityId = 16},
                new Neighborhood{Id = 904, Name = "Botun", CityId = 16},
                new Neighborhood{Id = 905, Name = "Brežine", CityId = 16},
                new Neighborhood{Id = 906, Name = "Bridje", CityId = 16},
                new Neighborhood{Id = 907, Name = "Brskut", CityId = 16},
                new Neighborhood{Id = 908, Name = "Budza", CityId = 16},
                new Neighborhood{Id = 909, Name = "Buronji", CityId = 16},
                new Neighborhood{Id = 910, Name = "Velje Brdo", CityId = 16},
                new Neighborhood{Id = 911, Name = "Veruša", CityId = 16},
                new Neighborhood{Id = 912, Name = "Vidijenje", CityId = 16},
                new Neighborhood{Id = 913, Name = "Vilac", CityId = 16},
                new Neighborhood{Id = 914, Name = "Vladni", CityId = 16},
                new Neighborhood{Id = 915, Name = "Vranj", CityId = 16},
                new Neighborhood{Id = 916, Name = "Vranjina", CityId = 16},
                new Neighborhood{Id = 917, Name = "Vrbica", CityId = 16},
                new Neighborhood{Id = 918, Name = "Vukovci", CityId = 16},
                new Neighborhood{Id = 919, Name = "Vuksanlekići", CityId = 16},
                new Neighborhood{Id = 920, Name = "Golubovci", CityId = 16},
                new Neighborhood{Id = 921, Name = "Goljemadi", CityId = 16},
                new Neighborhood{Id = 922, Name = "Goričani", CityId = 16},
                new Neighborhood{Id = 923, Name = "Gornje Stravče", CityId = 16},
                new Neighborhood{Id = 924, Name = "Gornji Kokoti", CityId = 16},
                new Neighborhood{Id = 925, Name = "Gornji Milješ", CityId = 16},
                new Neighborhood{Id = 926, Name = "Gostilj", CityId = 16},
                new Neighborhood{Id = 927, Name = "Gradac", CityId = 16},
                new Neighborhood{Id = 928, Name = "Grbavci", CityId = 16},
                new Neighborhood{Id = 929, Name = "Grbi Do", CityId = 16},
                new Neighborhood{Id = 930, Name = "Gurec", CityId = 16},
                new Neighborhood{Id = 931, Name = "Delaj", CityId = 16},
                new Neighborhood{Id = 932, Name = "Dinoša", CityId = 16},
                new Neighborhood{Id = 933, Name = "Dolovi", CityId = 16},
                new Neighborhood{Id = 934, Name = "Donje Stravče", CityId = 16},
                new Neighborhood{Id = 935, Name = "Donji Kokoti", CityId = 16},
                new Neighborhood{Id = 936, Name = "Donji Milješ", CityId = 16},
                new Neighborhood{Id = 937, Name = "Draževina", CityId = 16},
                new Neighborhood{Id = 938, Name = "Drešaj", CityId = 16},
                new Neighborhood{Id = 939, Name = "Drume", CityId = 16},
                new Neighborhood{Id = 940, Name = "Duga", CityId = 16},
                new Neighborhood{Id = 941, Name = "Dučići", CityId = 16},
                new Neighborhood{Id = 942, Name = "Dušići", CityId = 16},
                new Neighborhood{Id = 943, Name = "Duške", CityId = 16},
                new Neighborhood{Id = 944, Name = "Đurkovići", CityId = 16},
                new Neighborhood{Id = 945, Name = "Zagreda", CityId = 16},
                new Neighborhood{Id = 946, Name = "Zaugao", CityId = 16},
                new Neighborhood{Id = 947, Name = "Kiselica", CityId = 16},
                new Neighborhood{Id = 948, Name = "Klopot", CityId = 16},
                new Neighborhood{Id = 949, Name = "Kopilje", CityId = 16},
                new Neighborhood{Id = 950, Name = "Kornet", CityId = 16},
                new Neighborhood{Id = 951, Name = "Kosor", CityId = 16},
                new Neighborhood{Id = 952, Name = "Kotrabudan", CityId = 16},
                new Neighborhood{Id = 953, Name = "Koći", CityId = 16},
                new Neighborhood{Id = 954, Name = "Kržanja", CityId = 16},
                new Neighborhood{Id = 955, Name = "Kruse", CityId = 16},
                new Neighborhood{Id = 956, Name = "Krševo", CityId = 16},
                new Neighborhood{Id = 957, Name = "Kurilo", CityId = 16},
                new Neighborhood{Id = 958, Name = "Ljajkovići", CityId = 16},
                new Neighborhood{Id = 959, Name = "Lekići", CityId = 16},
                new Neighborhood{Id = 960, Name = "Lijeva Rijeka", CityId = 16},
                new Neighborhood{Id = 961, Name = "Liješnje", CityId = 16},
                new Neighborhood{Id = 962, Name = "Liješta", CityId = 16},
                new Neighborhood{Id = 963, Name = "Lovka", CityId = 16},
                new Neighborhood{Id = 964, Name = "Lopate", CityId = 16},
                new Neighborhood{Id = 965, Name = "Lužnica", CityId = 16},
                new Neighborhood{Id = 966, Name = "Lutovo", CityId = 16},
                new Neighborhood{Id = 967, Name = "Mataguži", CityId = 16},
                new Neighborhood{Id = 968, Name = "Mahala", CityId = 16},
                new Neighborhood{Id = 969, Name = "Medun", CityId = 16},
                new Neighborhood{Id = 970, Name = "Mileti", CityId = 16},
                new Neighborhood{Id = 971, Name = "Mitrovići", CityId = 16},
                new Neighborhood{Id = 972, Name = "Mojanovići", CityId = 16},
                new Neighborhood{Id = 973, Name = "Momče", CityId = 16},
                new Neighborhood{Id = 974, Name = "Mrke", CityId = 16},
                new Neighborhood{Id = 975, Name = "Mužeška", CityId = 16},
                new Neighborhood{Id = 976, Name = "Nabon", CityId = 16},
                new Neighborhood{Id = 977, Name = "Nikmaraš", CityId = 16},
                new Neighborhood{Id = 978, Name = "Ožezi", CityId = 16},
                new Neighborhood{Id = 979, Name = "Omerbožovići", CityId = 16},
                new Neighborhood{Id = 980, Name = "Opasanica", CityId = 16},
                new Neighborhood{Id = 981, Name = "Oraovice", CityId = 16},
                new Neighborhood{Id = 982, Name = "Orasi", CityId = 16},
                new Neighborhood{Id = 983, Name = "Orahovo", CityId = 16},
                new Neighborhood{Id = 984, Name = "Poprat", CityId = 16},
                new Neighborhood{Id = 985, Name = "Parci", CityId = 16},
                new Neighborhood{Id = 986, Name = "Pelev Brijeg", CityId = 16},
                new Neighborhood{Id = 987, Name = "Petrovići", CityId = 16},
                new Neighborhood{Id = 988, Name = "Pikalj", CityId = 16},
                new Neighborhood{Id = 989, Name = "Podhum", CityId = 16},
                new Neighborhood{Id = 990, Name = "Ponari", CityId = 16},
                new Neighborhood{Id = 991, Name = "Prisoja", CityId = 16},
                new Neighborhood{Id = 992, Name = "Prifti", CityId = 16},
                new Neighborhood{Id = 993, Name = "Progonovići", CityId = 16},
                new Neighborhood{Id = 994, Name = "Radeća", CityId = 16},
                new Neighborhood{Id = 995, Name = "Radovče", CityId = 16},
                new Neighborhood{Id = 996, Name = "Rakića Kuće", CityId = 16},
                new Neighborhood{Id = 997, Name = "Raći", CityId = 16},
                new Neighborhood{Id = 998, Name = "Releza", CityId = 16},
                new Neighborhood{Id = 999, Name = "Rijeka Piperska", CityId = 16},
                new Neighborhood{Id = 1000, Name = "Rudine", CityId = 16},
                new Neighborhood{Id = 1001, Name = "Selište", CityId = 16},
                new Neighborhood{Id = 1002, Name = "Seoca", CityId = 16},
                new Neighborhood{Id = 1003, Name = "Seoštica", CityId = 16},
                new Neighborhood{Id = 1004, Name = "Sjenice", CityId = 16},
                new Neighborhood{Id = 1005, Name = "Skorać", CityId = 16},
                new Neighborhood{Id = 1006, Name = "Slacko", CityId = 16},
                new Neighborhood{Id = 1007, Name = "Spinja", CityId = 16},
                new Neighborhood{Id = 1008, Name = "Srpska", CityId = 16},
                new Neighborhood{Id = 1009, Name = "Staniselići", CityId = 16},
                new Neighborhood{Id = 1010, Name = "Stanjevića Rupa", CityId = 16},
                new Neighborhood{Id = 1011, Name = "Stijena", CityId = 16},
                new Neighborhood{Id = 1012, Name = "Stjepovo", CityId = 16},
                new Neighborhood{Id = 1013, Name = "Stupovi", CityId = 16},
                new Neighborhood{Id = 1014, Name = "Sukuruć", CityId = 16},
                new Neighborhood{Id = 1015, Name = "Trabojin", CityId = 16},
                new Neighborhood{Id = 1016, Name = "Trmanje", CityId = 16},
                new Neighborhood{Id = 1018, Name = "Tuzi Ljevorečke", CityId = 16},
                new Neighborhood{Id = 1019, Name = "Ćafa", CityId = 16},
                new Neighborhood{Id = 1020, Name = "Ćepetići", CityId = 16},
                new Neighborhood{Id = 1021, Name = "Ubalac", CityId = 16},
                new Neighborhood{Id = 1022, Name = "Ubli", CityId = 16},
                new Neighborhood{Id = 1023, Name = "Farmaci", CityId = 16},
                new Neighborhood{Id = 1024, Name = "Fundina", CityId = 16},
                new Neighborhood{Id = 1025, Name = "Helmnica", CityId = 16},
                new Neighborhood{Id = 1026, Name = "Cvilin", CityId = 16},
                new Neighborhood{Id = 1027, Name = "Cijevna", CityId = 16},
                new Neighborhood{Id = 1028, Name = "Crvena Paprat", CityId = 16},
                new Neighborhood{Id = 1029, Name = "Crnci", CityId = 16},
                new Neighborhood{Id = 1030, Name = "Šušunja", CityId = 16},
                new Neighborhood{Id = 1031, Name = "Balotići", CityId = 17},
                new Neighborhood{Id = 1032, Name = "Bandžov", CityId = 17},
                new Neighborhood{Id = 1033, Name = "Bać", CityId = 17},
                new Neighborhood{Id = 1034, Name = "Bašča", CityId = 17},
                new Neighborhood{Id = 1035, Name = "Besnik", CityId = 17},
                new Neighborhood{Id = 1036, Name = "Bijela Crkva", CityId = 17},
                new Neighborhood{Id = 1037, Name = "Biševo", CityId = 17},
                new Neighborhood{Id = 1038, Name = "Bogaji", CityId = 17},
                new Neighborhood{Id = 1039, Name = "Bukovica", CityId = 17},
                new Neighborhood{Id = 1040, Name = "Vuča", CityId = 17},
                new Neighborhood{Id = 1041, Name = "Gornja Lovnica", CityId = 17},
                new Neighborhood{Id = 1042, Name = "Grahovo", CityId = 17},
                new Neighborhood{Id = 1043, Name = "Grižice", CityId = 17},
                new Neighborhood{Id = 1044, Name = "Dacići", CityId = 17},
                new Neighborhood{Id = 1045, Name = "Donja Lovnica", CityId = 17},
                new Neighborhood{Id = 1046, Name = "Ibarac", CityId = 17},
                new Neighborhood{Id = 1047, Name = "Jablanica", CityId = 17},
                new Neighborhood{Id = 1048, Name = "Kalače", CityId = 17},
                new Neighborhood{Id = 1049, Name = "Koljeno", CityId = 17},
                new Neighborhood{Id = 1050, Name = "Paučina", CityId = 17},
                new Neighborhood{Id = 1051, Name = "Plumci", CityId = 17},
                new Neighborhood{Id = 1052, Name = "Radetina", CityId = 17},
                new Neighborhood{Id = 1053, Name = "Seošnica", CityId = 17},
                new Neighborhood{Id = 1054, Name = "Sinanovići", CityId = 17},
                new Neighborhood{Id = 1055, Name = "Crnokrpe", CityId = 17},
                new Neighborhood{Id = 1056, Name = "Bogdašići", CityId = 18},
                new Neighborhood{Id = 1057, Name = "Bogišići", CityId = 18},
                new Neighborhood{Id = 1058, Name = "Gornja Lastva", CityId = 18},
                new Neighborhood{Id = 1059, Name = "Gošići", CityId = 18},
                new Neighborhood{Id = 1060, Name = "Donja Lastva", CityId = 18},
                new Neighborhood{Id = 1061, Name = "Đuraševići", CityId = 18},
                new Neighborhood{Id = 1062, Name = "Krasići", CityId = 18},
                new Neighborhood{Id = 1063, Name = "Lepetani", CityId = 18},
                new Neighborhood{Id = 1064, Name = "Milovići", CityId = 18},
                new Neighborhood{Id = 1065, Name = "Mrčevac", CityId = 18},
                new Neighborhood{Id = 1066, Name = "Radovići", CityId = 18},
                new Neighborhood{Id = 1067, Name = "Ambula", CityId = 19},
                new Neighborhood{Id = 1068, Name = "Bijela Gora", CityId = 19},
                new Neighborhood{Id = 1069, Name = "Bojke", CityId = 19},
                new Neighborhood{Id = 1070, Name = "Brajše", CityId = 19},
                new Neighborhood{Id = 1071, Name = "Bratica", CityId = 19},
                new Neighborhood{Id = 1072, Name = "Briska Gora", CityId = 19},
                new Neighborhood{Id = 1073, Name = "Vladimir", CityId = 19},
                new Neighborhood{Id = 1074, Name = "Gornja Klezna", CityId = 19},
                new Neighborhood{Id = 1075, Name = "Gornji Štoj", CityId = 19},
                new Neighborhood{Id = 1076, Name = "Darza", CityId = 19},
                new Neighborhood{Id = 1077, Name = "Donja Klezna", CityId = 19},
                new Neighborhood{Id = 1078, Name = "Donji Štoj", CityId = 19},
                new Neighborhood{Id = 1079, Name = "Draginje", CityId = 19},
                new Neighborhood{Id = 1080, Name = "Zoganj", CityId = 19},
                new Neighborhood{Id = 1081, Name = "Kaliman", CityId = 19},
                new Neighborhood{Id = 1082, Name = "Kodre", CityId = 19},
                new Neighborhood{Id = 1083, Name = "Kolonza", CityId = 19},
                new Neighborhood{Id = 1084, Name = "Kosići", CityId = 19},
                new Neighborhood{Id = 1085, Name = "Kravari", CityId = 19},
                new Neighborhood{Id = 1086, Name = "Kruta", CityId = 19},
                new Neighborhood{Id = 1087, Name = "Krute", CityId = 19},
                new Neighborhood{Id = 1088, Name = "Kruče", CityId = 19},
                new Neighborhood{Id = 1089, Name = "Leskovac", CityId = 19},
                new Neighborhood{Id = 1090, Name = "Lisna Bore", CityId = 19},
                new Neighborhood{Id = 1091, Name = "Međreč", CityId = 19},
                new Neighborhood{Id = 1092, Name = "Mide", CityId = 19},
                new Neighborhood{Id = 1093, Name = "Možura", CityId = 19},
                new Neighborhood{Id = 1094, Name = "Pistula", CityId = 19},
                new Neighborhood{Id = 1095, Name = "Rastiš", CityId = 19},
                new Neighborhood{Id = 1096, Name = "Reč", CityId = 19},
                new Neighborhood{Id = 1097, Name = "Salč", CityId = 19},
                new Neighborhood{Id = 1098, Name = "Sveti Đorđe", CityId = 19},
                new Neighborhood{Id = 1099, Name = "Sukobin", CityId = 19},
                new Neighborhood{Id = 1100, Name = "Sutjel", CityId = 19},
                new Neighborhood{Id = 1101, Name = "Ćurke", CityId = 19},
                new Neighborhood{Id = 1102, Name = "Fraskanjel", CityId = 19},
                new Neighborhood{Id = 1103, Name = "Šas", CityId = 19},
                new Neighborhood{Id = 1104, Name = "Štodra", CityId = 19},
                new Neighborhood{Id = 1105, Name = "Babaici", CityId = 20},
                new Neighborhood{Id = 1106, Name = "Barice", CityId = 20},
                new Neighborhood{Id = 1107, Name = "Bijedici", CityId = 20},
                new Neighborhood{Id = 1108, Name = "Bliskovo", CityId = 20},
                new Neighborhood{Id = 1109, Name = "Bojista", CityId = 20},
                new Neighborhood{Id = 1110, Name = "Boljanina", CityId = 20},
                new Neighborhood{Id = 1111, Name = "Boturici", CityId = 20},
                new Neighborhood{Id = 1112, Name = "Voljavac", CityId = 20},
                new Neighborhood{Id = 1113, Name = "Vrh", CityId = 20},
                new Neighborhood{Id = 1114, Name = "Godijevo", CityId = 20},
                new Neighborhood{Id = 1115, Name = "Godusa", CityId = 20},
                new Neighborhood{Id = 1116, Name = "Grab Bijelo Polje", CityId = 20},
                new Neighborhood{Id = 1117, Name = "Grancarevo", CityId = 20},
                new Neighborhood{Id = 1118, Name = "Gubavac", CityId = 20},
                new Neighborhood{Id = 1119, Name = "Dobrakovo", CityId = 20},
                new Neighborhood{Id = 1120, Name = "Dobrinje", CityId = 20},
                new Neighborhood{Id = 1121, Name = "Dolac - Bijelo Polje", CityId = 20},
                new Neighborhood{Id = 1122, Name = "Dubovo Bijelo Polje", CityId = 20},
                new Neighborhood{Id = 1123, Name = "Djalovici", CityId = 20},
                new Neighborhood{Id = 1124, Name = "ziljak", CityId = 20},
                new Neighborhood{Id = 1125, Name = "zurena", CityId = 20},
                new Neighborhood{Id = 1126, Name = "Zaton", CityId = 20},
                new Neighborhood{Id = 1127, Name = "Zminac", CityId = 20},
                new Neighborhood{Id = 1128, Name = "Ivanje - BIJELO Polje", CityId = 20},
                new Neighborhood{Id = 1129, Name = "Jablanovo", CityId = 20},
                new Neighborhood{Id = 1130, Name = "Jabucno", CityId = 20},
                new Neighborhood{Id = 1131, Name = "Jagoce", CityId = 20},
                new Neighborhood{Id = 1132, Name = "Kanje", CityId = 20},
                new Neighborhood{Id = 1133, Name = "Kicava", CityId = 20},
                new Neighborhood{Id = 1134, Name = "Kovren", CityId = 20},
                new Neighborhood{Id = 1135, Name = "Kostenica", CityId = 20},
                new Neighborhood{Id = 1136, Name = "Kostici", CityId = 20},
                new Neighborhood{Id = 1137, Name = "Kukulje", CityId = 20},
                new Neighborhood{Id = 1138, Name = "Lazovici", CityId = 20},
                new Neighborhood{Id = 1139, Name = "Laholo", CityId = 20},
                new Neighborhood{Id = 1140, Name = "Lekovina", CityId = 20},
                new Neighborhood{Id = 1141, Name = "Lijeska", CityId = 20},
                new Neighborhood{Id = 1142, Name = "Lozna", CityId = 20},
                new Neighborhood{Id = 1143, Name = "Loznica", CityId = 20},
                new Neighborhood{Id = 1144, Name = "Ljesnica - Bijelo Polje", CityId = 20},
                new Neighborhood{Id = 1145, Name = "Majstorovina", CityId = 20},
                new Neighborhood{Id = 1146, Name = "Metanjac", CityId = 20},
                new Neighborhood{Id = 1147, Name = "Milovo", CityId = 20},
                new Neighborhood{Id = 1148, Name = "Mioce", CityId = 20},
                new Neighborhood{Id = 1149, Name = "Mirojevici", CityId = 20},
                new Neighborhood{Id = 1150, Name = "Mojstir", CityId = 20},
                new Neighborhood{Id = 1151, Name = "Mokri Lug", CityId = 20},
                new Neighborhood{Id = 1152, Name = "Muslici", CityId = 20},
                new Neighborhood{Id = 1153, Name = "Negobratina", CityId = 20},
                new Neighborhood{Id = 1154, Name = "Nedakusi", CityId = 20},
                new Neighborhood{Id = 1155, Name = "Njegnjevo", CityId = 20},
                new Neighborhood{Id = 1156, Name = "Obrov", CityId = 20},
                new Neighborhood{Id = 1157, Name = "Okladi", CityId = 20},
                new Neighborhood{Id = 1158, Name = "Orahovica", CityId = 20},
                new Neighborhood{Id = 1159, Name = "Osmanbegovo Selo", CityId = 20},
                new Neighborhood{Id = 1160, Name = "Ostrelj", CityId = 20},
                new Neighborhood{Id = 1161, Name = "Pavino Polje", CityId = 20},
                new Neighborhood{Id = 1162, Name = "Pali", CityId = 20},
                new Neighborhood{Id = 1163, Name = "Pape", CityId = 20},
                new Neighborhood{Id = 1164, Name = "Pecarska", CityId = 20},
                new Neighborhood{Id = 1165, Name = "Pobretici", CityId = 20},
                new Neighborhood{Id = 1166, Name = "Poda - Bijelo Polje", CityId = 20},
                new Neighborhood{Id = 1167, Name = "Pozeginja", CityId = 20},
                new Neighborhood{Id = 1168, Name = "Potkrajci - Bijelo Polje", CityId = 20},
                new Neighborhood{Id = 1169, Name = "Potrk", CityId = 20},
                new Neighborhood{Id = 1170, Name = "Prijelozi", CityId = 20},
                new Neighborhood{Id = 1171, Name = "Pripcici", CityId = 20},
                new Neighborhood{Id = 1172, Name = "Ravna Rijeka", CityId = 20},
                new Neighborhood{Id = 1173, Name = "Radojeva Glava", CityId = 20},
                new Neighborhood{Id = 1174, Name = "Radulici", CityId = 20},
                new Neighborhood{Id = 1175, Name = "Rakita", CityId = 20},
                new Neighborhood{Id = 1176, Name = "Rakonje", CityId = 20},
                new Neighborhood{Id = 1177, Name = "Rasovo", CityId = 20},
                new Neighborhood{Id = 1178, Name = "Rastoka", CityId = 20},
                new Neighborhood{Id = 1179, Name = "Resnik", CityId = 20},
                new Neighborhood{Id = 1180, Name = "Rodijelja", CityId = 20},
                new Neighborhood{Id = 1181, Name = "Sadici", CityId = 20},
                new Neighborhood{Id = 1182, Name = "Sela - Bijelo Polje", CityId = 20},
                new Neighborhood{Id = 1183, Name = "Sipanje", CityId = 20},
                new Neighborhood{Id = 1184, Name = "Sokolac", CityId = 20},
                new Neighborhood{Id = 1185, Name = "Srdjevac", CityId = 20},
                new Neighborhood{Id = 1186, Name = "Stozer", CityId = 20},
                new Neighborhood{Id = 1187, Name = "Stubo", CityId = 20},
                new Neighborhood{Id = 1188, Name = "Tomasevo", CityId = 20},
                new Neighborhood{Id = 1189, Name = "Trubine", CityId = 20},
                new Neighborhood{Id = 1190, Name = "Ujnice", CityId = 20},
                new Neighborhood{Id = 1191, Name = "Unevine", CityId = 20},
                new Neighborhood{Id = 1192, Name = "Femica Krs", CityId = 20},
                new Neighborhood{Id = 1193, Name = "Cerovo - Bijelo Polje", CityId = 20},
                new Neighborhood{Id = 1194, Name = "Crnis", CityId = 20},
                new Neighborhood{Id = 1195, Name = "Crnca - Bijelo Polje", CityId = 20},
                new Neighborhood{Id = 1196, Name = "Crhalj", CityId = 20},
                new Neighborhood{Id = 1197, Name = "Ceoce", CityId = 20},
                new Neighborhood{Id = 1198, Name = "Cokrlije", CityId = 20},
                new Neighborhood{Id = 1199, Name = "Dzafica Brdo", CityId = 20},
                new Neighborhood{Id = 1200, Name = "Sipovice", CityId = 20},
                new Neighborhood{Id = 1201, Name = "Babića brijeg", CityId = 20},
                new Neighborhood{Id = 1202, Name = "Banje selo", CityId = 20},
                new Neighborhood{Id = 1203, Name = "Biokovac", CityId = 20},
                new Neighborhood{Id = 1204, Name = "Bioča", CityId = 20},
                new Neighborhood{Id = 1205, Name = "Bistrica", CityId = 20},
                new Neighborhood{Id = 1206, Name = "Brestovik", CityId = 20},
                new Neighborhood{Id = 1207, Name = "Brzava", CityId = 20},
                new Neighborhood{Id = 1208, Name = "Brčve", CityId = 20},
                new Neighborhood{Id = 1209, Name = "Vergaševići", CityId = 20},
                new Neighborhood{Id = 1210, Name = "Vrbe", CityId = 20},
                new Neighborhood{Id = 1211, Name = "Gojevići", CityId = 20},
                new Neighborhood{Id = 1212, Name = "Gorice", CityId = 20},
                new Neighborhood{Id = 1213, Name = "Gornji dio grada", CityId = 20},
                new Neighborhood{Id = 1214, Name = "Dupljaci", CityId = 20},
                new Neighborhood{Id = 1215, Name = "Kaševari", CityId = 20},
                new Neighborhood{Id = 1216, Name = "Kneževići", CityId = 20},
                new Neighborhood{Id = 1217, Name = "Kradenik", CityId = 20},
                new Neighborhood{Id = 1218, Name = "Krstače", CityId = 20},
                new Neighborhood{Id = 1219, Name = "Kruševo", CityId = 20},
                new Neighborhood{Id = 1220, Name = "Livadice", CityId = 20},
                new Neighborhood{Id = 1221, Name = "Lipnica", CityId = 20},
                new Neighborhood{Id = 1222, Name = "Ličine", CityId = 20},
                new Neighborhood{Id = 1223, Name = "Mahala", CityId = 20},
                new Neighborhood{Id = 1224, Name = "Medanovići", CityId = 20},
                new Neighborhood{Id = 1225, Name = "Nikoljac", CityId = 20},
                new Neighborhood{Id = 1226, Name = "Ograde", CityId = 20},
                new Neighborhood{Id = 1227, Name = "Oluja", CityId = 20},
                new Neighborhood{Id = 1228, Name = "Pisana jela", CityId = 20},
                new Neighborhood{Id = 1229, Name = "Pruška", CityId = 20},
                new Neighborhood{Id = 1230, Name = "Raklja", CityId = 20},
                new Neighborhood{Id = 1231, Name = "Ribarevine", CityId = 20},
                new Neighborhood{Id = 1232, Name = "Rijeke", CityId = 20},
                new Neighborhood{Id = 1233, Name = "Slatka", CityId = 20},
                new Neighborhood{Id = 1234, Name = "Strojtanica", CityId = 20},
                new Neighborhood{Id = 1235, Name = "Sutivan", CityId = 20},
                new Neighborhood{Id = 1236, Name = "Sušica", CityId = 20},
                new Neighborhood{Id = 1237, Name = "Ćukovac", CityId = 20},
                new Neighborhood{Id = 1238, Name = "Ušanovići", CityId = 20},
                new Neighborhood{Id = 1239, Name = "Centar grada", CityId = 20},
                new Neighborhood{Id = 1240, Name = "Čampar", CityId = 20},
                new Neighborhood{Id = 1241, Name = "Šolja", CityId = 20},
                new Neighborhood{Id = 1242, Name = "Bečići", CityId = 21},
                new Neighborhood{Id = 1243, Name = "Blizikuće", CityId = 21},
                new Neighborhood{Id = 1244, Name = "Boreti", CityId = 21},
                new Neighborhood{Id = 1245, Name = "Brajići I", CityId = 21},
                new Neighborhood{Id = 1246, Name = "Brajici II", CityId = 21},
                new Neighborhood{Id = 1247, Name = "Brajici III", CityId = 21},
                new Neighborhood{Id = 1248, Name = "Brajici IV", CityId = 21},
                new Neighborhood{Id = 1249, Name = "Brda", CityId = 21},
                new Neighborhood{Id = 1250, Name = "Buljarica I", CityId = 21},
                new Neighborhood{Id = 1251, Name = "Buljarica II", CityId = 21},
                new Neighborhood{Id = 1252, Name = "Viti Do", CityId = 21},
                new Neighborhood{Id = 1253, Name = "Drobnići", CityId = 21},
                new Neighborhood{Id = 1254, Name = "Đenaći", CityId = 21},
                new Neighborhood{Id = 1255, Name = "Zukovica", CityId = 21},
                new Neighborhood{Id = 1256, Name = "Ilino Brdo", CityId = 21},
                new Neighborhood{Id = 1257, Name = "Kaluderac I", CityId = 21},
                new Neighborhood{Id = 1258, Name = "Kaluderac II", CityId = 21},
                new Neighborhood{Id = 1259, Name = "Katun Rezevići", CityId = 21},
                new Neighborhood{Id = 1260, Name = "Krstac", CityId = 21},
                new Neighborhood{Id = 1261, Name = "Kuljače", CityId = 21},
                new Neighborhood{Id = 1262, Name = "Kuljačce Dapkovici", CityId = 21},
                new Neighborhood{Id = 1263, Name = "Lapčići", CityId = 21},
                new Neighborhood{Id = 1264, Name = "Markovići", CityId = 21},
                new Neighborhood{Id = 1265, Name = "Markovici Duletici", CityId = 21},
                new Neighborhood{Id = 1266, Name = "Novoselje I", CityId = 21},
                new Neighborhood{Id = 1267, Name = "Novoselje II", CityId = 21},
                new Neighborhood{Id = 1268, Name = "Petrovac na Moru", CityId = 21},
                new Neighborhood{Id = 1269, Name = "Pobori", CityId = 21},
                new Neighborhood{Id = 1270, Name = "Pobori Gornji", CityId = 21},
                new Neighborhood{Id = 1271, Name = "Podbabac", CityId = 21},
                new Neighborhood{Id = 1272, Name = "Podostrog I", CityId = 21},
                new Neighborhood{Id = 1273, Name = "Podostrog II", CityId = 21},
                new Neighborhood{Id = 1274, Name = "Przno I", CityId = 21},
                new Neighborhood{Id = 1275, Name = "Przno II", CityId = 21},
                new Neighborhood{Id = 1276, Name = "Prijevor I", CityId = 21},
                new Neighborhood{Id = 1277, Name = "Prijevor II", CityId = 21},
                new Neighborhood{Id = 1278, Name = "Radjenovići", CityId = 21},
                new Neighborhood{Id = 1279, Name = "Rijeka Rezevići", CityId = 21},
                new Neighborhood{Id = 1280, Name = "Sveti Stefan", CityId = 21},
                new Neighborhood{Id = 1281, Name = "Stanisići", CityId = 21},
                new Neighborhood{Id = 1282, Name = "Tudorovići", CityId = 21},
                new Neighborhood{Id = 1283, Name = "Cami Do", CityId = 21},
                new Neighborhood{Id = 1284, Name = "Celobrdo", CityId = 21},
                new Neighborhood{Id = 1285, Name = "Cucuke", CityId = 21},
                new Neighborhood{Id = 1286, Name = "Andrijevica", CityId = 1},
                new Neighborhood{Id = 1287, Name = "Bar", CityId = 2},
                new Neighborhood{Id = 1288, Name = "Žabljak", CityId = 3},
                new Neighborhood{Id = 1289, Name = "Šavnik", CityId = 4},
                new Neighborhood{Id = 1290, Name = "Berane", CityId = 5},
                new Neighborhood{Id = 1291, Name = "Cetinje", CityId = 6},
                new Neighborhood{Id = 1292, Name = "Danilovgrad", CityId = 7},
                new Neighborhood{Id = 1293, Name = "Herceg Novi", CityId = 8},
                new Neighborhood{Id = 1294, Name = "Kolašin", CityId = 9},
                new Neighborhood{Id = 1295, Name = "Kotor", CityId = 10},
                new Neighborhood{Id = 1296, Name = "Mojkovac", CityId = 11},
                new Neighborhood{Id = 1297, Name = "Nikšić", CityId = 12},
                new Neighborhood{Id = 1298, Name = "Plav", CityId = 13},
                new Neighborhood{Id = 1299, Name = "Pljevlja", CityId = 14},
                new Neighborhood{Id = 1300, Name = "Plužine", CityId = 15},
                new Neighborhood{Id = 1301, Name = "Podgorica", CityId = 16},
                new Neighborhood{Id = 1302, Name = "Rožaje", CityId = 17},
                new Neighborhood{Id = 1303, Name = "Tivat", CityId = 18},
                new Neighborhood{Id = 1304, Name = "Ulcinj", CityId = 19},
                new Neighborhood{Id = 1305, Name = "Bijelo Polje", CityId = 20},
                new Neighborhood{Id = 1306, Name = "Budva", CityId = 21},
                new Neighborhood{Id = 1307, Name = "Tuzi", CityId = 22},
                new Neighborhood{Id = 1308, Name = "Petnjica", CityId = 23},
                new Neighborhood{Id = 1309, Name = "Gusinje", CityId = 24}

            };

        return neighborhoods;
    }
}